### PR TITLE
Update font awesome

### PR DESCRIPTION
**Pull request by MichaelBuessemeyer**
This PR update font awesome to the newest version to add some more awesome icons.

### URL of deployed dev instance (used for testing):
- https://upgradefa.webknossos.xyz

### Steps to test:
- Look at each component on the deployed branch that has a font awesome icon
- The icon should be correctly displayed and the icon "type" should be the same

### Issues:
- No issue -> needed for #4755

------
- ~~[ ] Updated [(unreleased) changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)~~
- ~~[ ] Updated [(unreleased) migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes~~
- ~~[ ] Needs datastore update after deployment~~
- [x] Ready for review

### CODE REVIEW

**Review by daniel-wer — COMMENTED** [review]
Thanks for updating :+1: 

I found only one instance where icons were not shown, the group and the colored circle in the tree tab (see screenshot for what it should look like).
tree-icons

**Comment by MichaelBuessemeyer** [comment]
> I found only one instance where icons were not shown, the group and the colored circle in the tree tab (see screenshot for what it should look like).


I cannot reproduce this error :confused:. This picture is from the deployed dev branch. Could you please check this again? 
image

**Comment by MichaelBuessemeyer** [comment]
@daniel-wer As the others already tested your fix-> Let's merge?

**Review by daniel-wer — APPROVED** [review]
:+1:

**Pull request merged**
