### PR TITLE
Fix welcome notification on wk.org

### PR DESCRIPTION
**Pull request by hotzenklotz**
This PR is a follow up for the antd v5 upgrade and fixes the styling of the "Welcome"/"Sign up for free" notification on wk.org. 

**Before**:
image

**After**:
image

### Steps to test:
- Copy the URI/link to a dataset for them the toolbar
- Open the link in an incognito browser window
- The welcome notification should show

### Issues:
- follow up to #6861 

------
(Please delete unneeded items, merge only when none are left open)
- [x] Updated [changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [ ] Updated [migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Removed dev-only changes like prints and application.conf edits
- [x] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [ ] Needs datastore update after deployment

### CODE REVIEW

**Review by philippotto — COMMENTED** [review]
I assume this is ready for review? Code looks good, but one thing:

The learn more button is a bit hard to read when it's hovered (independent of dark / light mode):

image

**Comment by hotzenklotz** [comment]
> I assume this is ready for review? Code looks good, but one thing:

Yes, it is ready.

> The learn more button is a bit hard to read when it's hovered (independent of dark / light mode):
> 
> image

Not really sure what to do about this. It is an antd `ghost` button and that is the default behavior: https://ant.design/components/button?theme=dark#components-button-demo-ghost

**Comment by hotzenklotz** [comment]
> > Not really sure what to do about this.
> 
> Can you slap on a class which changes the hovering color? Since the bg is always blue, it should be independent of the theme.

Done

**Review by philippotto — APPROVED** [review]
nice, thank you!

**Pull request merged**
