### PR TITLE
Task list should only show tasks one can administrate

### LINKED ISSUE #4041: Team Manager can't access tasks' annotations
How to reproduce (may not be accurate due to 🍻):
- You are a Team Manager
- There are tasks you created, were done and are finished now
- Open the task list and try to access the finished annotations

### PR DESCRIPTION
**Pull request by youri-k**
### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- open task list if you are a team manager in one team and a user in another one
- task list should only show task from the team where you're team manager

### Issues:
- fixes #4041 

------
- [x] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)
- [x] Ready for review

### CODE REVIEW

**Comment by youri-k** [comment]
This is a pretty naive solution but it works and doesn't change the sql query, so I thought this would fix the problem :slightly_smiling_face:

**Comment by youri-k** [comment]
>  The current version probably breaks pagination, as this is handled on top of the SQL query, leading to possibly fewer results per page.
Good catch! I forgot about that. I now added a `listAccessQ` that is similar to the `deleteAccessQ` because it adds the needed extra condition :slightly_smiling_face:

**Comment by jstriebel** [comment]
> I now added a `listAccessQ` that is similar to the `deleteAccessQ` because it adds the needed extra condition

Nice! That's actually even simpler than before. Just rename the whole access query to `administrateAccessQ`, that fits both cases. The setup to test this is quite complex, so I'd skip this if you tested this thoroughly.

**Comment by youri-k** [comment]
I don't think this works because the `deleteAccessQ` is a member of the base class and is used in `deleteOne` for instance. We could think about using the `deleteAccessQ` in the list query and adding a comment but I'm not sure if this is really better

**Pull request merged**
