### PR TITLE
Simple fix to speed up dataset gallery

### LINKED ISSUE #3442: Paginate Dataset Gallery
this should save load both in server and client since not all thumbnails are then requested at the same time

related: #3418

### PR DESCRIPTION
**Pull request by daniel-wer**
This is a very simple proposal to speed up the dataset gallery page for instances with a single organization. Previously in that case, all datasets (and their thumbnails) were shown and we thought about implementing pagination and/or viewport dependent rendering.
Now, when loading the page only the first 6 datasets are shown. A "Show more" link can be clicked to show all datasets (same as in the multiple-organizations-case, as on demo.webknossos).
I would argue that this alone will result in a decrease in server load as in most cases not all thumbnails are loaded. The search box still searches through all datasets and works as before.

If users complain about having to click that button or are doing it very often, we can always implement viewport dependent rendering later, I'd say :)

/cc @fm3 

### URL of deployed dev instance (used for testing):
- https://speedupspotlight.webknossos.xyz

### Steps to test:
- Open the gallery dataset view. Clicking "Show More" should show all datasets. Even having not clicked on "Show More", all datasets should be searchable.

### Issues:
- fixes #3442

------
- [ ] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)
- [x] Ready for review

### CODE REVIEW

**Comment by jfrohnhofen** [comment]
Regarding reducing pressure on the backend: The thumbnails have been / should be cached. So this should not really affect the server much in a production setup. Maybe the caching in the backend is broken causing the long loading times in the first place?

**Comment by daniel-wer** [comment]
Could very well be, but still, requesting ~266 thumbnails (on master), each around 200kb in size is not really necessary, let's save some bandwidth :) I think most of the times, this view is opened to search through the existing datasets (which is still possible) or by accident or because it's the default tab.

**Comment by jfrohnhofen** [comment]
Yes, sure. I did not want to discredit your PR, just in addition this is something we should check.

**Comment by daniel-wer** [comment]
I fully agree with you :)

**Comment by fm3** [comment]
Cool stuff, thanks!
Regarding the back-end cache, I checked it recently when we first spoke about this performance issue, and it works still. However, the mhlab instance is frequently updated (restarted), resetting this cache, so the case of re-creating all thumbnails was not actually that rare. Also, sending hundreds of not-so-small images at the same time is not nothing, even if they are already in the cache.

**Comment by jfrohnhofen** [comment]
@fm3 Thanks for checking!

**Pull request merged**
