### PR TITLE
Make Frontpage Mobile-Friendly

### LINKED ISSUE #3890: Make frontpage usable on mobile
Some low hanging fruits to make the frontpage more usable on mobile. This is necessary for our SEO ranking (bad mobile UX will be downranked).

- Organize login into dropdown (see #3765) 
- [Set viewport](http://html5-mobile.de/blog/meta-viewport-fuer-mobile-anpassen) maybe to 600px
- Adapt publication gallery to work with the smaller viewport

### PR DESCRIPTION
**Pull request by hotzenklotz**
Google Search complains, the wK.org is not mobile optimized. Therefore, I tried to improve this. What I did so far:

- add viewport `<meta>` tag
- some CSS adjustments for the header & spotlight view
- specified different grid size for large and small displays in spotlight view.

The `<meta>` tag typically restricts the browser viewport to the device width, which in turn is the basis for all the grids, media queries etc. This works well for regular web pages, but not great for wK.

Goal of the PR is not get wK ready for a great mobile experience. My focus was exclusively on the frontpage ("spotlight"), "Features", and "Pricing". Those look reasonably well. Opening a dataset is another story... 

## Discussion
1. Perhaps, we should only active the "mobile-friendly" frontpage on wk.org and not on other instances?
2. It would be great if we could have the `<meta>` tag only on the frontpage and not once you are logged in / viewing a dataset. I don't know a good way to enforce that though.

### URL of deployed dev instance (used for testing):
- https://mobile.webknossos.xyz

### Steps to test:
- Try https://mobile.webknossos.xyz on many devices. Perhaps BrowserStack?

### Issues:
- fixes #3890 
------
- [X] Ready for review

Some Screenshots:
"Pixel 2"
localhost_9000_(Pixel 2)

"iPhone X"
localhost_9000_(iPhone X)

"iPad"
localhost_9000_(iPad)

### CODE REVIEW

**Comment by hotzenklotz** [comment]
# Discussion
1. Perhaps, we should only active the "mobile-friendly" frontpage on wk.org and not on other instances?
2. It would be great if we could have the <meta> tag only on the frontpage and not once you are logged in / viewing a dataset. I don't know a good way to enforce that though.

@normanrz @philippotto @daniel-wer @fm3 Any thoughts / ideas?

**Comment by daniel-wer** [comment]
Nice work, thanks for including the screenshots! :)

> Perhaps, we should only active the "mobile-friendly" frontpage on wk.org and not on other instances?

I'd say this isn't very important if we restrict the changes to the spotlight/pricing changes only (see point 2), but we could easily include the meta tag only on demo, nevertheless.

> It would be great if we could have the tag only on the frontpage and not once you are logged in / viewing a dataset. I don't know a good way to enforce that though.

Yes I agree with that. With the current state of the PR, wK becomes pretty much unusable on mobile when logged in/viewing a dataset which would be a regression. Before, although zoomed out very much, you could still use it on mobile. I don't have a quick idea on how to accomplish that, I'll think about it.


Can you somehow see/test what Google Search thinks about the site at https://mobile.webknossos.xyz (has the rating improved)?

P.S. The results on my Honor 8 don't look as nice as the screenshots, for some reason the viewport is still a little bigger than my phone screen and the text overflows to the right. Feel free to drop by to have a look. Maybe my phone screen is simply too small ^^

**Comment by philippotto** [comment]
> * Perhaps, we should only active the "mobile-friendly" frontpage on wk.org and not on other instances?

I think it's better to have the behavior uniform across domains. Otherwise, testing and debugging can easily become too convoluted.

> * It would be great if we could have the  tag only on the frontpage and not once you are logged in / viewing a dataset. I don't know a good way to enforce that though.

I pushed a commit which removes the mobile-friendly viewport meta tag if the user is authenticated OR if the tracing view is opened. The change is not undone when the user logs out or the tracing page is left. I think this is alright, though (otherwise, implementation effort would have been to high).

@daniel-wer Can you review my commit please? :)

**Comment by daniel-wer** [comment]
@philippotto LGTM, nice solution with the small React component :) Did you test whether this works already?

**Comment by normanrz** [comment]
Wouldn't it make more sense to tie the viewport to routes in the Router (i.e. only for publication view etc)?

**Comment by normanrz** [comment]
And, I think we can omit the wk logo on "iPad" as well.

**Comment by philippotto** [comment]
> Did you test whether this works already?

Yes, it's tested :tada: 

> Wouldn't it make more sense to tie the viewport to routes in the Router (i.e. only for publication view etc)?

I think the idea was to have the mobile viewport meta tag by default so that google's crawlers pick it up without any problems (in contrast to dynamically adding the tag at run time). Thus, blacklisting the tag via the logged-in-or-tracing criterion seemed like the simplest choice.

**Comment by philippotto** [comment]
> And, I think we can omit the wk logo on "iPad" as well.

I'm not sure what you mean by that? Do you mean the `webKnossos` text in the navbar? That should be hidden on mobile in general?

**Comment by normanrz** [comment]
>>And, I think we can omit the wk logo on "iPad" as well.

>I'm not sure what you mean by that? Do you mean the webKnossos text in the navbar? That should be hidden on mobile in general?

I did not mean the navbar, but the hero block (when you look at the phone screenshots it is already hidden)

**Comment by normanrz** [comment]
> I think the idea was to have the mobile viewport meta tag by default so that google's crawlers pick it up without any problems (in contrast to dynamically adding the tag at run time). Thus, blacklisting the tag via the logged-in-or-tracing criterion seemed like the simplest choice.

The tag could be there by default and stripped away through the router? But, I'm also fine with the current solution :+1:

**Comment by philippotto** [comment]
@daniel-wer Can you approve? :)

**Pull request merged**
