### PR TITLE
merge demo flags

### LINKED ISSUE #4008: merge demo feature flags into one

### PR DESCRIPTION
**Pull request by youri-k**
### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- wK should work as before

### Issues:
- fixes #4008 

------
- [ ] Ready for review

### CODE REVIEW

**Comment by youri-k** [comment]
@MichaelBuessemeyer I removed all backend usages of the config flags but not yet removed them from the config. I'll do that once you're finished with the frontend.

**Comment by MichaelBuessemeyer** [comment]
@youri-k I adjusted the frontend to not use `enableFrontpage, addMissingDatasetButtonEnabled, alowOrganizationCreation` anymore. Feel free to remove all of the completely from wk :slightly_smiling_face:

**Comment by youri-k** [comment]
corresponding kube pr https://github.com/scalableminds/kube/pull/250

**Comment by MichaelBuessemeyer** [comment]
@youri-k Could you please merge this together with the kube pr?

**Pull request merged**
