### PR TITLE
Fix Android panning to move in plane

### LINKED ISSUE #3780: Fix panning on Android
(Seems to work on iOS, I think)

As a dirty workaround, the following might work. However, we should try to get hammerjs to do exactly what we want without those quirks.

```diff
diff --git a/frontend/javascripts/libs/input.js b/frontend/javascripts/libs/input.js
index 3cac88bb4..6b47f7c48 100644
--- a/frontend/javascripts/libs/input.js
+++ b/frontend/javascripts/libs/input.js
@@ -549,6 +549,11 @@ export class InputMouse {
   getRelativeMousePosition = (pagePosition: { pageX: number, pageY: number }) => {
     const offset = this.getElementOffset();

+    if (pagePosition.pageX === null) {
+      pagePosition.pageX = pagePosition.touches[0].pageX;
+      pagePosition.pageY = pagePosition.touches[0].pageY;
+    }
+
     return {
       x: pagePosition.pageX - offset.left,
       y: pagePosition.pageY - offset.top,
```

### PR DESCRIPTION
**Pull request by MichaelBuessemeyer**
This PR fixes the in-plane movement triggered by panning on touch screen devices. The problem specifically occurred for android phones.

### URL of deployed dev instance (used for testing):
- https://fixandroidpanning.webknossos.xyz

### Steps to test:
- Open the dev instance on your mobile phone and simply view a dataset or open a tracing.
- Panning in one of the viewports should move the viewed plane of that viewport around.

### Issues:
- fixes #3780

------
- ~~[ ] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)~~
- ~~[ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes~~
- ~~[ ] Needs datastore update after deployment~~
- [x] Ready for review

### CODE REVIEW

**Comment by MichaelBuessemeyer** [comment]
While debugging this a bit I noticed that if the user pans on a viewport, a `TouchEvent` is given by hammerjs. This is a collection of [w3c specified `TouchEvents`](https://www.w3.org/TR/touch-events/#touch-interface). If the user pans somewhere else (not viewport), the typical `MouseEvent` is given which has the `pageX/pageY` property.

At least this is where the bug is coming from and why the workaround seems to solve this bug.

**Comment by MichaelBuessemeyer** [comment]
After a closer look, I found that the Touch Event returned by hammerjs exactly follows the specification: https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent

**Comment by MichaelBuessemeyer** [comment]
I just looked at this again, and I would not call these changes a "workaround" anymore (at least not an unpleasant one). Because we use the same method to determine a position for typical mouse events and for touch events. But mouse events and touch events do not have the same interface. This is why this if statement is necessary and thus this is not an unpleasant workaround but also not ideal :)

**Comment by normanrz** [comment]
Works well!

**Pull request merged**
