### PR TITLE
force invalidation of old datasets to finish, before new datasets are…

### LINKED ISSUE #2291: Dataset will not permanently import
https://discuss.webknossos.org/t/dataset-will-not-permanently-import/687

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2291/create?referer=github" target="_blank">Log Time</a>

### PR DESCRIPTION
**Pull request by jfrohnhofen**
… written to DB, fixes #2291

When datasets are reported from a datastore to wK, the datasets in the database are updated in a two-step process:
1) set all datasets from the reporting datastore to the "no longer available" state
2) update all datasets received from the datastore
This is a lazy way of invalidating no longer available datasets, since the datastore does not explicitly tell wk about those (but only implicitly by omitting them)

With the old code, these two updates were executed in parallel, causing some datasets to be updated first and then invalidated. This PR enforces the invalidation to complete, before any updated datasources are written to the DB.

### Mailable description of changes:
 - Bugfix: datasets no longer automatically un-import themselves

### Steps to test:
- this is difficult to test locally, since this happens due to a race-condition in the database
- if you have many (> 100) imported datasets, calling `data/triggers/checkInbox` will (without the fix) cause some of them to un-import. after this PR, all datasets should stay imported.

### Issues:
- fixes #2291 

------
- [x] Ready for review

### CODE REVIEW

**Comment by normanrz** [comment]
What would it take to achieve this behavior w/o de-activating all datasets in the db?

**Comment by jfrohnhofen** [comment]
something along the lines of `db.datasets.update({"datasource.id.name": {$nin: [ list of all reported datasets ]}})`. Do you see any real benefit in this?

**Comment by normanrz** [comment]
Seems to me like a more robust way of fixing this issue. But I can't estimate how much comm-effort between datastore and wK this would entail.

**Comment by jfrohnhofen** [comment]
@fm3 @normanrz Please have another look.

**Pull request merged**
