### PR TITLE
Handle Cross-Datastore Duplicates, introducing scratch datastores

### LINKED ISSUE #3391: Updating datasets on datastore report should also consider organization
both deactivateUnreported ~~and updateDataSource~~ seem lax about this

### PR DESCRIPTION
**Pull request by fm3**
### Steps to test:
- setup two standalone datastores
- have a dataset in both datastores
- if one of the datastores is marked as `isScratch = true` in the db, the datasets from the other one should have precedence. Otherwise, whichever was reported first stays.

### Issues:
- fixes #3391
- contributes to #3369 

------
- ~~[ ] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)~~
- ~~[ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Needs datastore update after deployment~~
- [x] Ready for review

### CODE REVIEW

**Comment by fm3** [comment]
@jfrohnhofen https://github.com/scalableminds/webknossos/wiki/Set-up-a-standalone-datastore-locally

(slightly more complex to start a second one, I checked out the repo a second time, and there replaced the 9090 by 9091)

**Comment by fm3** [comment]
@jfrohnhofen cool, thanks :)

**Comment by jstriebel** [comment]
@fm3 @jfrohnhofen The migration note is missing in this PR, I'll add it in #3414

**Comment by fm3** [comment]
good catch, sorry about that.

**Pull request merged**
