### PR TITLE
Fix creating a task using a base NML

### PR DESCRIPTION
**Pull request by philippotto**
### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- open the "create a task" dialog
- select "Upload NML File" and upload an NML
- fill the remaining values
- create a task --> should work

### Issues:
- follow-up for https://github.com/scalableminds/webknossos/pull/6486/files

------
(Please delete unneeded items, merge only when none are left open)
- [x] Updated [(unreleased) changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [ ] Updated [(unreleased) migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Needs datastore update after deployment
- [X] Ready for review

### CODE REVIEW

**Review by fm3 — COMMENTED** [review]
I’m afraid this breaks task creation *without* nml.

Note that the form and bulk task creation use the same request unless NMLs are added, so there will probably be a need to distinguish between with or without NML for this field

**Comment by philippotto** [comment]
Hm, ok, then, I'd suggest that the backend should always accept/expect `taskTypeIdOrSummary`. Would this be alright?

**Comment by fm3** [comment]
I created a new PR for the backend version https://github.com/scalableminds/webknossos/pull/6635

**Review by hotzenklotz — APPROVED** [review]
🚀

**Comment by philippotto** [comment]
Closed in favor of #6635.

**Pull request closed without merging**
