### PR TITLE
Add shortcut to maximize golden layout panes

### LINKED ISSUE #3926: Add shortcut to maximize pane
Should maximize the pane that "contains" the mouse cursor.

### PR DESCRIPTION
**Pull request by daniel-wer**
This is the best I could come up with. keyboardjs doesn't easily allow to set a "target element" and keyup event handlers can only be attached at the document level, so I had to get a little more involved. What do you think? :)

~~Of course the shortcut is debatable, I picked M for Maximize, ideally it would be a single key press, but there have been voices in the community to avoid those.~~
The shortcut is `.` now.

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- Open tracing view, move mouse over any pane and press `.` to toggle maximize.

### Issues:
- fixes #3926 

------
- [ ] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)
- [x] Ready for review

### CODE REVIEW

**Comment by fm3** [comment]
just noting that ctrl+m is “mute tab” in firefox, but since wk doesn’t produce sound, I guess it is fair to overwrite that :)

**Comment by normanrz** [comment]
I guess just `m` would be a good shortcut. I don't know what the concerns with single-key shortcuts are, but we do have a bunch of them already.

From a code perspective, would it be feasible to have a keyboard shortcuts defined in one place?

**Comment by daniel-wer** [comment]
@philippotto Thanks for your feedback, you were right with both suggestions, I switched to using a single keyboardjs handler :)

The shortcut is now `.`

> From a code perspective, would it be feasible to have a keyboard shortcuts defined in one place?
@normanrz I see the benefit of this, but I think it would be rather complicated or at least I don't have a good idea how to do that. We should definitely pay attention to keeping the shortcut overview up-to-date, so we're not losing track for now.

**Comment by normanrz** [comment]
nice. looking forward to tweet about this :bird:

**Pull request merged**
