### PR TITLE
Hybrid task with nml

### LINKED ISSUE #4117: Hybrid tasks with given NML
[Link to Discuss](https://discuss.webknossos.org/t/volume-tracing-with-given-nml/1485)

@fm3 When you have a few minutes, could you give a rough estimation about how much work this would require for the back-end? 1h? 4h? More than that? :)

For the front-end, I'd estimate 4 hours.

### LINKED ISSUE #4187: Hybrid tasks with given segmentation
Related to #4117.

### PR DESCRIPTION
**Pull request by youri-k**
- [x] blocked by performance problems of creating/duplicating volume tracings

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- create explorative annotation as baseAnnotation and copy the id
- create new task with the copied id as baseAnnotationId
- get task and see the baseAnnotation 

### Issues:
- fixes #4117 
- fixes #4187 

------
- [x] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)
- ~~[ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes~~
- ~~[ ] Needs datastore update after deployment~~
- [x] Ready for review

### CODE REVIEW

**Comment by youri-k** [comment]
Frontend ToDo: 
- [ ] show field for baseAnnotation in non-bulk view
- [ ] adapt the json format `"baseAnnotation": {"baseId": "id"}`

**Comment by philippotto** [comment]
front-end is done!

**Comment by philippotto** [comment]
Thank you for the thorough testing @daniel-wer! I didn't notice that the base annotation type takes precedence. However, I'd suggest to fix this already in this PR, since I think it's a likely scenario that hybrid tasks should be created and the base annotation is only a skeleton. The other direction ("create skeleton task and base is hybrid") might be less likely, but I think that should be even easier to fix, @youri-k?

So, I guess these two to dos remain for the back end:
- [ ] if a hybrid base annotation is provided for a skeleton or volume task, only the respective skeleton or volume tracing should be written into the task base (thus, preventing that the task turns into a hybrid)
- [ ] if a non-hybrid base annotation is provided for a hybrid task, then the back end should create an empty tracing for the missing companion tracing

@youri-k Do you agree with this plan?

**Comment by philippotto** [comment]
@fm3 @youri-k Do you think we can land this? As far as I know, the most recent performance logging showed that this is no longer blocked. Is this correct?

**Comment by fm3** [comment]
I’d possibly add a warning to the user that this is a slow operation, and should not be done with too many tasks at a time, something like this. What do you think @philippotto ? Apart from that, I guess we can merge and deploy.

**Pull request merged**
