### PR TITLE
Fix screenshot tests

### LINKED ISSUE #6592: Nightly screenshot tests fail
Currently the nightly screenshot tests fail, one particular segment of a segmentation screenshot seems to be invisible. We should either investigate or skip this test so the rest of the nightly becomes useful again.

### PR DESCRIPTION
**Pull request by daniel-wer**
By always initializing mapping color texture with EMPTY_KEY. Otherwise, the content of the texture is undefined which led to issues during our automated nightly tests (presumably, because the texture contained lots of 1s, segment 1 was not rendered correctly).

### URL of deployed dev instance (used for testing):
- https://fixcuckootextureinit.webknossos.xyz

### Steps to test:
- CI is sufficient

### Issues:
- fixes #6592 

------
(Please delete unneeded items, merge only when none are left open)
- [ ] Updated [(unreleased) changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [x] Ready for review

### CODE REVIEW

**Comment by daniel-wer** [comment]
@philippotto This was actually the fix :tada:

I updated some more screenshots, because the error toast that was partly visible in some of them no longer appears and because the meshes are now smoothed. If all screenshot tests except for the connectome one succeed this should be ready to go (the connectome viewer is not enabled for this branch) once the temporary changes are reverted.

**Comment by daniel-wer** [comment]
Screenshot tests look good: https://app.circleci.com/pipelines/github/scalableminds/webknossos/8868/workflows/bc5ac41a-3c51-47a1-9d88-3002de4e6cea/jobs/20233/steps (see my last comment for why the connectome dataset fails)

**Review by philippotto — APPROVED** [review]
Awesome :raised_hands:

**Comment by philippotto** [comment]
I hope it's alright if I merge this PR already. From my side, it's looking very good :) Then, we can have a green nightly tonight hopefully :crossed_fingers: Otherwise, a follow-up should do it.

**Pull request merged**
