### PR TITLE
Partly scrollable tables

### LINKED ISSUE #4106: Ensure that antd tables are not too wide
Can be provoked by zooming in.

### LINKED ISSUE #4225: Indicator for scrollability
The optimized dataset table is good, but people don't understand that the table can be scrolled  horizontally. Perhaps we can add a visual indicator for scrollability.

Bildschirmfoto 2019-08-07 um 18 01 55

### PR DESCRIPTION
**Pull request by MichaelBuessemeyer**
This PR makes all large tables partly scrollable to make them responsive.

### URL of deployed dev instance (used for testing):
- https://partlyscrollabletables.webknossos.xyz/

### Steps to test:
- I changed the following tables. Please look at them on the dev instance and tell me if something looks weird or if you have suggestions to improve some parts.
  - dashboard: 
      - dataset table
      -  explorative annotations table
  - admin:
      - script list table
      - open tasks table
      - project progress table
      -  task list table
      - task type creation -> enable recommended settings, the table on the right
      - task type table
      - user table
      - recommended configuration model

### Issues:
- fixes #4225
- Also fixes  #4106 as the tables should look fine in chrome too.

### Please note
- At least one column shouldn't have a set width. That makes it possible for the table to spread this column freely to make the table responsive.

------
- ~~[ ] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)~~
- ~~[ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes~~
- ~~[ ] Needs datastore update after deployment~~
- [x] Ready for review

### CODE REVIEW

**Comment by MichaelBuessemeyer** [comment]
@normanrz @philippotto @hotzenklotz There is still something unclear for me: How far do we want to support the responsibility? 
If I reduce the width of my browser by half I get the following, which works perfectly fine with 3 fixed columns: 
medium-width
<br/><br/>
<br/><br/>
But when I decrease the width even further the three fixed columns cover up all space and the scrollable columns are not visible:
small-width

One solution would be to have only 2 fixed columns (e.g. one on the right and one on the left.

Currently I have 3 fixed columns in most cases.

**Comment by normanrz** [comment]
I think there is no reason to fix the 2nd column. Imo the 1st column also doesn't need to be fixed.

**Comment by philippotto** [comment]
I agree with @normanrz. Only the last column should be fixed. The motivation of this issue is that people should know that elements on the right side of the table might be cut-off. The left side of the table is visible by default when loading the page. So, there's no need to fix anything.

**Comment by MichaelBuessemeyer** [comment]
> I agree with @normanrz. Only the last column should be fixed.

@philippotto Now only the last column is fixed (sometimes when it does not make any sense no column is fixed). 
You can review this PR. I added some data on the dev instance so that almost every table should have at least one row of data.

**Pull request merged**
