### PR TITLE
Fewer error messages in view mode

### LINKED ISSUE #5046: Failure in saving dataSetConfiguration causes UI crash
I’m getting the »Failed to save annotation. Retrying.« Toast even in view mode and the »Internal error.
Please reload the page to avoid losing data. [object Object] undefined« alert.

Saving dataSetConfiguration should not be that important, maybe this error can be (more) silently ignored, while still logging it to airbrake

### PR DESCRIPTION
**Pull request by MichaelBuessemeyer**
This PR reduces the possible error messages displayed in view only mode.
The two errors that are now ignored in view only mode are:
- The error that is show when the updating the tracing fails.
- The error that is show when saving the users dataset settings fails.

### URL of deployed dev instance (used for testing):
- https://lesserrormessagesinviewmode.webknossos.xyz

### Steps to test:
- I only found out how to reproduce the second error (locally):
  - Open a dataset in view mode and when it is loaded kill your local server.
  - The open the dataset settings an eg. enable/disable the "Render Isosurfaces (Beta)"-setting. This should not trigger an error.
  - If you try the same on the master, the tracing should enter the "error state" and an alert should be displayed. 

### Issues:
- fixes #5046

------
- ~~[ ] Updated [(unreleased) changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)~~
- ~~[ ] Updated [(unreleased) migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes~~
- ~~[ ] Needs datastore update after deployment~~
- [x] Ready for review

### CODE REVIEW

**Review by daniel-wer — COMMENTED** [review]
Could you add that errors are still logged to airbrake? Otherwise we may never know about them.
For example, my assumption would be that the update actions save queue is always empty in view mode and it would be very interesting if (and how/why) this assumption might not hold.

Apart from that, LGTM :+1:

**Comment by MichaelBuessemeyer** [comment]
@daniel-wer I just added the airbrake notification for view mode only.  :). Could you please give this a check (whether I used the notify method correctly)?

**Comment by daniel-wer** [comment]
@MichaelBuessemeyer looks good to me. Please also add this to the other spot where an error is suppressed :+1:

**Review by daniel-wer — APPROVED** [review]
LGTM, worked as expected during testing :+1:

**Comment by philippotto** [comment]
Accidentally closed by #5049.

**Pull request merged**
