### PR TITLE
Always update PRs

### PR DESCRIPTION
**Pull request by normanrz**
This config change would always update PR branches, regardless of the `automerge` label. I think this could be useful, but I am looking for other opinions.

------
- [x] Ready for review

### CODE REVIEW

**Comment by fm3** [comment]
I’m not convinced the benefits outweigh the downsides
 + possibly less wait time before merging
 + less diversion of branches due to automatic updates (except in case of conflicts I guess)

 − lots of circleci runs so the ones we actually wait for may not get scheduled (also unnecessary energy consumed)
 − you can’t push your changes until you pull (including the new master) – sometimes I want to push at the end of the day but not worry about changes from master

**Comment by philippotto** [comment]
I agree with @fm3. Additionally, I think, that it can get annoying when the git history is polluted by frequent merges.

**Comment by daniel-wer** [comment]
Thanks for the proposal, but I'm agreeing with @fm3 and @philippotto, the `automerge` label is sufficient :)

**Comment by normanrz** [comment]
Thanks for your feedback. I'll close this PR then.

**Pull request closed without merging**
