### PR TITLE
update changelog and migration guide for 19.06.0 release

### PR DESCRIPTION
**Pull request by jstriebel**
- [x] Ready for review

### CODE REVIEW

**Comment by fm3** [comment]
@MichaelBuessemeyer @philippotto is the changelog line “Non-admin users now can see their own tracing time statistics” correct for this version of the code? If I remember correctly that was split into two parts. Is that all in here?

**Comment by MichaelBuessemeyer** [comment]
@fm3 Thanks for noticing. "Non-admin users now can see their own tracing time statistics." is indeed not correct at the moment. There is currently no why for an non-admin user to access the time tracking view. Although the view should be accessable via url manipulation. And I think the view would also display the data because the backend route got reworked to do so.

But as the view is not offically opened to non-admin users, I think this changelog entry should be removed

**Comment by MichaelBuessemeyer** [comment]
I took initialtive and updated the change log. I hope thats alright 🙂  @fm3 @jstriebel

**Comment by jstriebel** [comment]
Perfect, thanks @MichaelBuessemeyer. I also removed it from the `Added` Block for now, let's add it again when it's easily accessible.

**Pull request merged**
