### PR TITLE
remove dataStoreToken rom config and use sth random instead

### PR DESCRIPTION
**Pull request by jfrohnhofen**
### Steps to test:
- open wK do sth that needs the wk-token (e.g. download a volume tracing or create a tracing)
- be happy that it still works

------
- [ ] Ready for review

### CODE REVIEW

**Comment by jstriebel** [comment]
PR to remove the config parameter for our deployment:
https://github.com/scalableminds/kube/pull/71

**Comment by jfrohnhofen** [comment]
WARNING: do not merge, until fossilDB is used in production

**Comment by jfrohnhofen** [comment]
@jstriebel do we use fossil in prod everywhere?

**Comment by fm3** [comment]
@jfrohnhofen I believe @jstriebel said that the dev server will switch to fossildb only after it is part of the cluster… or something like that, meaning that this issue is blocked for a little longer

**Comment by jfrohnhofen** [comment]
The main reason this was blocked by FossilDB is, that calling the backup routes is no longer possible, since the token is unknown. This should not matter on dev, since we don't backup rocksdb there, I think.
but does that mean (since fossil is already in master), that we can't deploy the current master on the dev server?

**Comment by fm3** [comment]
Ok I can’t estimate those problems, if jstriebel thinks its okay with the current setup, we can merge all of the fossildb stuff and this.

FossilDB is not actually used in the master branch yet. While the startup scripts there do start a fossildb process, webknossos still uses the libs version 11.3.9 which handles rocksdb directly, as before. So for now, this fossildb process is idle.

**Comment by jstriebel** [comment]
Current status:
Only the external datastores for `mhlab` run with FossilDB. Currently we can't deploy `dev` instances or `demo` with fossildb. Let's wait until norman or I added this to our helm setup and we all use the new `dev` environment.

**Comment by jstriebel** [comment]
@jfrohnhofen , @fm3 
As fossildb is almost merged (#2235), could you resolve the conflicts in the imports? I'm not sure which ones to take here.

**Pull request merged**
