### PR TITLE
Enable dead-code-elimination in production

### PR DESCRIPTION
**Pull request by hotzenklotz**
React spams the console and Airbrake with warnings about being deployed in production. The recommend solution is to apply dead code elimination for production builds.

image

Docs:
https://reactjs.org/docs/optimizing-performance.html#use-the-production-build

### Steps to test:
- Make sure CI builds correctly

------
- [x] Ready for review

### CODE REVIEW

**Comment by normanrz** [comment]
This means that we always need sourcemaps to look at code in production, right?
Are we cool with that? @philippotto @daniel-wer

**Comment by daniel-wer** [comment]
This has been the case since we enabled uglify, I think, as variable/function name mangling was enabled there. This PR only adds dead-code-elimination.
I'm cool with needing source maps anyways, the specific source map types I enabled in the uglify PR seem to work quite well.

**Comment by philippotto** [comment]
> This means that we always need sourcemaps to look at code in production, right?
Are we cool with that? @philippotto @daniel-wer

Fine by me!

**Comment by normanrz** [comment]
Alright :-)

**Pull request merged**
