### PR TITLE
lower histogram clip threshold a bit

### LINKED ISSUE #5990: Follow-up to auto contrast/brightness
- [x] bug: the button is only positioned correct for the first layer. the other layers are seemingly missing the button (it is rendered on top of the first button due to `absolute` positioning)
- [x] bug: prevent clip button from moving with very long layer names
- [x] UX: when the button was clicked, the full quality data is loaded first which can take some seconds. during that time, the button should turn into a spinner to indicate that something is happening
- [ ] lower the clipping threshold ratio a bit
- (next iteration: allow to tune the intensity degree of the normalization (e.g., the thresholdRatio?))
- (next iteration: continuous auto-contrast (when moving through data the normalization could be done again?))

### PR DESCRIPTION
**Pull request by Dagobert42**
### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- use histogram clip button

### Issues:
- fixes #5990 

------
- [x] Ready for review

### CODE REVIEW

**Review by fm3 — COMMENTED** [review]
Thanks a lot for looking into this!

For the datasets I used this for, I believe 3% is still clipping away too much.

The way I understand this, the clip values are only there because of noise in the image data. Is this correct?
If the image data has no noise, I would want to see all present brightness values, because anything that is mapped above 1 or below 0 is undesired loss of information – so in case of no noise I would want this clip value to be 0.
Noise means brighter and darker pixels are present than the “effective” brightness range of the “real” data. This is why clip value 0 would fit those in, making the “effective” data bland.
This corresponds to what I described in #5163 
So what we really want is to de-noise the image (e.g. by slightly blurring it – or just take the histogram from higher mags, which are already kind of blurred) and then use clip value 0. The effect of using different mags can already be tested by zooming out. Try for example this (very noisy) public EM dataset https://webknossos.org/datasets/MPI_Brain_Research/2020-06-12-p5-align2/view#3447,5165,2560,0,30.867 – there, in mag1 the strong 5% already look ok because of the heavy noise. In higher mags (denoised), 5% is way too aggressive.
Until we can have that, I would rather err on the side of displaying bland data instead of accidentally clipping away interesting data. So I would argue for something way lower, like 0.5 %.

Do you agree @Dagobert42  @philippotto ?

**Comment by Dagobert42** [comment]
Thanks for the detailed feedback :) 
I see! I've lowered the clipping value even more for a start. 

As I understood, the intention was to overexaggerate the contrast a bit. But then we would actually want a sort of noise estimation or noise level function? I will see if I can find any simple algortihms for this.

**Review by fm3 — APPROVED** [review]
Thanks a lot! :) I see, but I’d think overexaggerating the contrast is usually not the user’s wish. I may be wrong though :shrug:. Let’s see if we get external feedback on this.

I think you don’t need to look further into the denoising for now. This is a good follow-up issue (I just wrote https://github.com/scalableminds/webknossos/issues/6115) that we may schedule at a later time.

**Comment by philippotto** [comment]
> As I understood, the intention was to overexaggerate the contrast a bit. But then we would actually want a sort of noise estimation or noise level function? I will see if I can find any simple algortihms for this.

If I understood @fm3 correctly, a simple blur pass before creating the histogram could be enough? See [here](https://img.ly/blog/how-to-apply-filters-in-javascript/) the code beginning with `if (filter === "blur") {` as an example.

I agree with @fm3 and think this is something for another PR for which we should figure out the priority later :)

**Pull request merged**
