### PR TITLE
Update docker compose commands + dev install readme

### PR DESCRIPTION
**Pull request by MichaelBuessemeyer**
### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- Update to docker compose v2 and check whether `./start-docker.sh` works.

### CODE REVIEW

**Comment by MichaelBuessemeyer** [comment]
@fm3 I don't know who to assign to this pr. As you requested / suggested this pr, I just assigned you to it :sweat_smile:

**Comment by fm3** [comment]
Sure, I’ll do some testing. Do you happen to have installation instructions for the required docker and docker-compose versions for ubuntu 22.04 LTS?

**Comment by fm3** [comment]
nvm, found something :)

**Review by fm3 — APPROVED** [review]
LGTM. I took the liberty to add some more updates to the dev_install readme.

Note that production instances are usually not run with yarn commands or commands from dev_install. The docs at https://docs.webknossos.org/webknossos/installation.html already refer to the new docker compose.

Our own hosted instances in kubernetes do not use docker compose. I also double-checked that the dev deployment still works.

We do host some datastores with the old docker compose on external servers, but that should continue to work after these changes. Upgrading those is a separate issue.

**Comment by MichaelBuessemeyer** [comment]
> LGTM. I took the liberty to add some more updates to the dev_install readme.

Thanks a lot :tada:

**Pull request merged**
