### PR TITLE
dump & diff postgres schema

### LINKED ISSUE #2556: Assert that updated SQL Schema is equivalent to original one + evolutions
<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2556/create?referer=github" target="_blank">Log Time</a>

### LINKED ISSUE #2655: local development: find better way to check if schema is up-to-date
maybe with the same mechanisms as #2556 ?

### PR DESCRIPTION
**Pull request by jstriebel**
### TODO:
* [x] make folder customizable to allow diffs
* [x] add script for diffs (should allow for an actual db or a bunch of sql scripts)
* [x] this should not take into account the line order
* [x] add CI check that `tools/postgres/schema.sql` and `conf/evolutions/*` agree (fixes #2556)
* [x] check that no evolution number is used twice
* [x] produce a warning/error on startup, if schema does not fit (fixes #2655, also useful in production)
* [x] Bug: triggers and functions seem to be missing in dump

#### after deployment:
* [ ] run evolution `014`, make sure that the production instances agree with schema.sql

### Steps to test:
- check output on local startup with an up-to-date and an outdated schema
- check that the e2e tests fail, if the evolutions and schema.sql don't agree (see CI build before commit `equalize schema and evolutions`)
- double check in code review that the production databases can not be altered or dropped by those changes
- test evolution `014`

### Issues:
- fixes #2556 and #2655
------
- [x] Ready for review

### CODE REVIEW

**Comment by jstriebel** [comment]
@fm3: I just added the diffing script for the schemas. Currently the evolutions don't run without errors on a fresh database. You can try it on this branch with
```
docker-compose run --rm compile tools/postgres/diff_schema.sh tools/postgres/schema.sql "conf/evolutions/*.sql"
```
This would diff the `evolutions` against `schema.sql` (currently it still looks at the line order, I will fix that next).

Could you have a look at the evolutions, if they can be fixed easily? I guess you are still more familiar with them than me. If not I'll try to fix them myself.

**Comment by jstriebel** [comment]
@fm3: I just added the fallback for `POSTGRES_URL`, does it work for you?

@norman: Could you review the bash scripts `tools/postgres/diff_schema.sh` & `tools/postgres/dump_schema.sh`? Everything else is reviewed by @fm3 .

**Comment by fm3** [comment]
@jstriebel unfortunately it does not, as your fallback is only for `ORIGINAL_POSTGRES_URL`, but `POSTGRES_URL` is also used in line 14 independently

**Comment by jstriebel** [comment]
Yes, refactoring the `diff_schema` script is a good idea. I'm just not sure if python is the right choice, because
a) it adds a huge dependency to wk, and
b) I think its stdlib syntax for processes is to complex for scripting.

To fix the process syntax simple libraries or custom functions might be fine. Also http://xon.sh/tutorial.html might be worth a glance.
I could also rewrite this script in Scala, might be worth a try:
https://alvinalexander.com/scala/how-to-write-scala-shell-scripts-scripting-language-examples

What do you think, @normanrz ? If this is not a major blocker, we might also defer this decision to Sunday/Monday, to discuss it in person, and do it in a separate PR.

**Comment by normanrz** [comment]
Ok, we can do that in a different PR.

Maybe python isn't the right choice. How about node with [commander](https://www.npmjs.com/package/commander)? I feel that Scala may be a bit too fat for this and I wouldn't want a new language/toolchain that we're not familiar with for this.

**Comment by jstriebel** [comment]
Node is a good idea! :bulb:  I added #2779 for this.

**Pull request merged**
