### PR TITLE
upgrade grpc and use new fossildb standard health check

### PR DESCRIPTION
**Pull request by fm3**
### note: needs datastore upgrade

- use the new fossilDB that comes with the standardized grpc health check
- use that health check
- add checking it to the datastore’s own health endpoint
- use new versions of protobuf/grpc dependencies (package structure changed)
- get rid of the scalapb-json4s dependency (as we are not sending protobuf as json anymore since #2650)

### Steps to test:
- Set up: [Here is how to set up a standalone-datastore locally](https://github.com/scalableminds/webknossos-wiki/wiki/Set-up-a-standalone-datastore-locally)
- Create a new task & try to get a new task --> should work
- Get another new task -> should fail with no datastore-related error message
- Open a dataset --> should work
- Kill the fossildb
- Create a new task & try to get a new task --> should fail with a warning about the datastore
- Open a dataset --> shouldn't display data (but instead warn about the datastore)

### Issues:
- contributes to #2604

------
- [x] Ready for review

### CODE REVIEW

**Comment by fm3** [comment]
Let us defer this until #2650 is merged, because then the backend does not need scalapb-json4s anymore at all

**Comment by jstriebel** [comment]
currently testing this locally

**Comment by jstriebel** [comment]
I can't get data from the external datastore running locally in Docker. I added some changes to be able to run this in docker. Some parts of it should probably go into master, but to make it reproducible, I pushed all of my changes to [`upgrade-grpc-docker`](https://github.com/scalableminds/webknossos/compare/upgrade-grpc...upgrade-grpc-docker).
I ran the following commands to start wk with the external datastore:
```
export DOCKER_TAG=upgrade-grpc
docker-compose pull webknossos webknossos-datastore
docker-compose run --entrypoint ./tools/postgres/refresh_schema.sh webknossos
docker-compose run psql
	select * from webknossos.datastores;
	truncate webknossos.datastores;
	select * from webknossos.datastores;
	insert into webknossos.datastores(name, url, key, typ, isdeleted) values('standalone-9090', 'http://webknossos-datastore:9090', 'something-secur3', 'webknossos-store', false);
	select * from webknossos.datastores;
	\q
docker-compose up webknossos webknossos-datastore
```

Then the log of webknossos shows the following after the datastore connects to it:
```
[DEBUG] controllers.WKDataStoreController - Status update from data store 'standalone-9090'. Status: true
[ERROR] models.binary.DataSetSQLDAO$ - SQL Error: org.postgresql.util.PSQLException: ERROR: syntax error at or near ")"
  Position: 167
  Location: File: scan.l, Routine: scanner_yyerror, Line: 1087
  Server SQLState: 42601
[DEBUG] models.binary.DataSetSQLDAO$ - Caused by query:
  <empty line>
```

The datastore prints
```
[ERROR] - from com.scalableminds.util.rpc.RPCRequest in ForkJoinPool-2-worker-1
  Unsuccessful WS request to http://webknossos:9000/api/datastores/standalone-9090/datasources (ID: 1).Status: 400. Response: {"messages":[{"error":"SQL Failure: ERROR: syntax error at or near \")\"\n  Position: 167\n  Locatio
```

When clicking `Refresh` in the `datasets` view, I get a toast saying
```
The datastore server at http://webknossos-datastore:9090 does not seem to be available. This is likely due to an update. Please check back in five minutes.
```

Probably something with my setup is not right, but I tried to stick to [this documentation](https://github.com/scalableminds/webknossos-wiki/wiki/Set-up-a-standalone-datastore-locally).

@fm3 Maybe let's debug this together tomorrow.

**Comment by jstriebel** [comment]
Two more things:
* We should upgrade fossildb in the repo as well (in `fossildb/version` and `docker-compose.yml`)
* Why is the smoke test in the CI running through, even if we haven't upgraded fossildb?

**Comment by fm3** [comment]
@jstriebel the error message does not look docker-related on first glance, let’s look at this together tomorrow.
I think I updated fossildb/version in this PR. not docker-compose, though, I suppose that should be added.

**Comment by fm3** [comment]
@jstriebel you’re experiencing #2695 . I’ll create a PR for that but it should not block this one.

**Comment by jstriebel** [comment]
When running this without fossildb, and try to get a new Task (even though there shouldn't be one), I get `Failed to retrieve annotation base`, but no error about the datastore.

When I should be able to get a task, I get:
`Failed to use annotation base as template.`
and
`The datastore server at http://webknossos-datastore:9090 does not seem to be available. This is likely due to an update. Please check back in five minutes.`


For tracing a Dataset, I get the expected
```
The datastore server at http://webknossos-datastore:9090 does not seem to be available. This is likely due to an update. Please check back in five minutes.
```
and for adding a task
`Line 0: could not save to FossilDB: UNAVAILABLE: Unable to resolve host fossildb ` :heavy_check_mark:

**Pull request merged**
