### PR TITLE
Support cyclic trees

### LINKED ISSUE #2130: Make sure cyclic trees are supported
Cyclic trees have been disallowed in webknossos since the beginning and cannot be created from within webknossos. However, as at some point the error message indicating that got lost, users started to upload NMLs with cyclic trees, which I think leads to subtle bugs and errors. If I remember correctly there are parts of the code that assume that there will be no cyclic trees.

This issue should be the base for discussion on whether webknossos should support cyclic trees and if so to make sure that it actually supports them.

Bugs that were probably caused by this:
https://discuss.webknossos.org/t/webknossos-produces-invalid-nml-files-multiple-comments-per-node/556/5
https://discuss.webknossos.org/t/tasks-do-not-load/566/6

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2130/create?referer=github" target="_blank">Log Time</a>

### PR DESCRIPTION
**Pull request by daniel-wer**
This PR adds support for cyclic trees (they're not really trees any longer ^^). The warning in the abstract tree viewer regarding cyclic trees was broken, opening the tab resulted in an infinite loop that nearly crashed my system. I've added a small cycle check and render an error message if a cyclic tree was detected.
The only other place I could find that assumed non-cyclic trees was the deleteNode/deleteEdge functionality. I've fixed this as well.

We should also think about whether we want to allow to create cyclic trees from within webknossos. Currently the merge functionality will not allow this, and maybe this is fine - we could wait for the lab to request that feature.

Does anyone else know of other places in the code that assume there are no cyclic trees? (@normanrz @hotzenklotz @philippotto)

@jfrohnhofen As far as I know, the backend makes no assumptions about the absence of cycles in trees, right?

### Mailable description of changes:
 - Cyclic trees/graphs are now officially supported by webKnossos. Splitting/Merging actions on those trees will no longer break tracings.

### Steps to test:
- Upload this nml [cyclic.nml.zip](https://github.com/scalableminds/webknossos/files/1461491/cyclic.nml.zip) or create other cyclic nmls
- Split trees, undo, redo, try to break webknossos - webknossos should not break :D

### Issues:
- fixes #2130

------
- [x] Ready for review

### CODE REVIEW

**Comment by jfrohnhofen** [comment]
We never process entire tracings so we don't really care about their (tree) structure; the only thing we do is apply update actions. I doubt that any of these rely on trees being trees, but @fm3 knows this for sure.

**Comment by fm3** [comment]
I agree, pretty sure they don’t. The other place to look is the [NmlParser](https://github.com/scalableminds/webknossos/blob/master/app/models/annotation/nml/NmlParser.scala#L116)(does some stuff like splitting trees into connected components) but that looks like it should also not be affected by trees containing cycles.

**Comment by philippotto** [comment]
> Does anyone else know of other places in the code that assume there are no cyclic trees? (@normanrz @hotzenklotz @philippotto)

I'm not aware of anything other than what you took care of :)

> We should also think about whether we want to allow to create cyclic trees from within webknossos. Currently the merge functionality will not allow this, and maybe this is fine - we could wait for the lab to request that feature.

Yes, I would wait for the lab to bring that up.

**Comment by hotzenklotz** [comment]
Here are my testing observatiions when using the supplied `cyclic.nml` file:
- After uploading and opening the NML there was no active node. Consequently, when I create my first node, it was connected to the cyclic tree. Yet, it was still counted as belonging to the original tree even though there was no edge.
- After uploading and opening the NML the abstract tree viewer was completely empty / white. The cyclic tree error message only appear after setting a node.
- The abstract tree viewer does not seem use newlines. The error message is out of the window for me: 
image

Other then the mentioned stuff, it seems to work fine. Good job.


> Does anyone else know of other places in the code that assume there are no cyclic trees? 
The only thing that I can think of that is somewhat related, is the tree merge operation. Currently, we actively block creating an edge that would result in a cycle. I think that is fine for now.

**Comment by daniel-wer** [comment]
@hotzenklotz Thanks for the thorough testing! Regarding the missing activeNodeId, that was actually a bug in the skeletontracing initializer. Whenever the server sent no activeNodeId before, we chose an active tree, but forgot to choose an activeNode as well. Fixing this fixed your second point as well.

There is no newline, because canvas `drawText` doesn't support newlines ^^ I've shortened the message and moved it left - it should be displayed in full now, otherwise the user needs to scroll.

**Pull request merged**
