### PR TITLE
upload dataset view sends organization now instead of team

### LINKED ISSUE #2473: can’t upload dataset (error.required)
<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2473/create?referer=github" target="_blank">Log Time</a>

### PR DESCRIPTION
**Pull request by fm3**
Fixed the upload dataset view to work with organizations. Previously, all datasets were assigned to a team by default. Now datasets belong directly to an organization.

### Steps to test:
- Go to Dashboard --> Gallery View --> "Upload Dataset"
- Upload a dataset. --> should work
- Testing Datasets can be downloaded from the wiki

### Issues:
- fixes #2473

------
- [ ] Ready for review

### CODE REVIEW

**Comment by fm3** [comment]
merge should come with updating the datastore to the new version

**Comment by hotzenklotz** [comment]
@fm3 A short question: Are newly uploaded datasets assigned to any team by default? The organization's team?

**Comment by fm3** [comment]
@hotzenklotz that’s right, I just tested the upload (your fix seems to work) and the organization team is automatically added to the allowed teams.

**Comment by fm3** [comment]
@tom since the backend changes here are so small, I think you can go ahead with philipp’s frontend-only review. Note that upon deployment we should also upgrade the datastore to the new version

**Pull request merged**
