### PR TITLE
Panel content and new controls followup

### LINKED ISSUE #5611: Make sure the icons work with dark mode
## Expected Behavior
The icon should be white

## Current Behavior
Screenshot 2021-07-08 at 13 05 21

## Steps to Reproduce the bug
1. Context menu in annotation mode

## Your Environment for bug
* Browser name and version: Chrome 91
* Operating System and version: macOS 11.4
* Version of WebKnossos (Release or Commit): 15071

### PR DESCRIPTION
**Pull request by MichaelBuessemeyer**
Two simple fixes of issues probably caused by the panel reorganization and new shortcuts or so.

This PR also unifies the naming for the context menu in the frontend. Thus there are some more line changes than necessary.

### URL of deployed dev instance (used for testing):
- https://panelcontentandnewcontrolsfollowup.webknossos.xyz

### Steps to test:
- Open a dataset with a segmentation layer in view mode
- New new keyboard shortcuts mode
- Open the context menu while hovering a segment
- There should be the option to load the matching precomputed mesh (but it is probably not selectable)
- The copy segment id icon should now support dark mode (to test this, switch to dark mode). The icon should then be white. 

### Issues:
- fixes #5611 #5610 #5620 

------
- ~~[ ] Updated [(unreleased) changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)~~
- ~~[ ] Updated [(unreleased) migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes~~
- ~~[ ] Needs datastore update after deployment~~
- [x] Ready for review

### CODE REVIEW

**Comment by fm3** [comment]
Just a heads-up about a potential merge conflict here, to avoid extra confusion: If my understanding is correct this contains a version of #5618 – but PR #5402, which was merged to day, also solved that. I am not familiar with the code, feel free to decide which version too keep :)

**Comment by MichaelBuessemeyer** [comment]
@daniel-wer / @fm3 Could you please review the newest changes?
I unified the behaviour of loading meshes via the meshes tab and the meshes context menu option. These changes were tested using the ROI dataset with a precomputed meshes file.

**Review by fm3 — APPROVED** [review]
Works for me :) I can’t really speak about the code quality (the latest commit includes the master merge so it is hard to see which changes are new) but from my side this is Ok now

**Comment by MichaelBuessemeyer** [comment]
>I can’t really speak about the code quality (the latest commit includes the master merge so it is hard to see which changes are new) but from my side, this is Ok now

I took a close look myself and there aren't many changes and the code looks fine to me. As @daniel-wer will only be available later, I'll merge this PR now to be able to deploy the fixes. 

If there are some coding style mistakes you find @daniel-wer, please tell me and I will incorporate them into another PR :)

**Comment by daniel-wer** [comment]
> If there are some coding style mistakes you find @daniel-wer, please tell me and I will incorporate them into another PR :)

All good, thanks for pushing through with this :+1:

**Pull request merged**
