### PR TITLE
Added more space between tree names and checkbox

### LINKED ISSUE #4120: Toggling tree visibility changes position
In [this tracing](https://webknossos.brain.mpg.de/annotations/Explorational/5cf507c6010000a1bb0fac79#143330,152162,1993,0,1.026,90207), when I toggle the visibility of different trees, the position changes. Is this intended? Is there a way to prevent it?

### PR DESCRIPTION
**Pull request by hotzenklotz**
Issues #4120 describes that tree toggling moves the wK position. One speculation is, that the user is miss-clicking the checkbox for toggling a tree. Consequently, the tree is selected / clicked and wK jumps to the tree's position.

As a workaround, I added slightly more margin between the checkbox and tree name / text to avoid accidental misclicks. Hopefully this mitigates the issue somewhat.

### Steps to test:
- Start a skeleton tracing
- create a few tree
- click on the checkboxes to toggle the trees
- slightly miss-clicking the checkbox should not invoke a jump / select a tree

### Issues:
- potentially fixes #4120

------
- [ ] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)
- [ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes
- [ ] Needs datastore update after deployment
- [x] Ready for review

### CODE REVIEW

**Comment by hotzenklotz** [comment]
@daniel-wer Yes, I ask Georg. He didn't know  how to reproduce it and suggest this fix instead/in the meantime.

**Comment by hotzenklotz** [comment]
I double checked with Georg and we noticed something else. Clicking on the checkmark moves the position back to active node's positions. Hence you only notice movement when the camera is not centered on the active node's position.

I don't see this behavior with my fix anymore.

**Comment by daniel-wer** [comment]
I see, great, thanks for fixing :tada:

**Comment by hotzenklotz** [comment]
From what I can see, click the checkbox also triggered the `onClick` handler for the whole row/entry. That handler does something with tree selection. I move this `onClick` handler to only cover the text entry and NOT the checkmark. 

I guess this solves the root cause.

**Pull request merged**
