### PR TITLE
Clean up temporary upload files

### LINKED ISSUE #4884: Follow-Up resumable upload: clean up orphan file chunks
If resumable uploads, as introduced in #4860 fail (server down etc), orphan file chunks may be left on disk. Those should be cleaned up periodically. Check if their name is present in the live wK’s upload chunk registry

### PR DESCRIPTION
**Pull request by youri-k**
### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- start upload, but do not complete it
- restart wk
- => temporary upload file should be gone

### Issues:
- fixes #4884 

------
- ~~[ ] Updated [(unreleased) changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)~~
- ~~[ ] Updated [(unreleased) migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes~~
- [x] Needs datastore update after deployment
- [x] Ready for review

### CODE REVIEW

**Comment by youri-k** [comment]
This checks for orphan file chunks only on server restart because that is the only way elements are removed from the map without being deleted from the disk as well. I don't know, if that's enough, given that some wK instances run for an extended period of time. We could introduce some long timeout, e.g. 10 days, maybe even a month, that ensures this cleanup job is not dependent on server restarts.

**Review by fm3 — COMMENTED** [review]
LGTM. I think that rare execution on startup is ok.
Do you know if it impacts wk startup time?
If so, maybe do this asynchronously, like 60s after startup?
I’d also suggest adding logging to see which files are deleted (in case anything is ever wrongly deleted then we will have a means to debug that)

**Comment by youri-k** [comment]
> Do you know if it impacts wk startup time?
I tried to measure it with around 10 broken uploads and it took around 50ms, so I wouldn't expect any negative impact. Do you expect more broken uploads?

I added some logging now :slightly_smiling_face:

**Review by fm3 — APPROVED** [review]
Ok cool that shouldn’t be a problem then :)  Thanks for checking!

**Pull request merged**
