### PR TITLE
deactiveate resetting the scale on datasource deactivation, #2316

### PR DESCRIPTION
**Pull request by jfrohnhofen**
### Steps to test:
- create a skeleton tracing on a dataset
- make that already imported dataset unavailable (e.g. by deleting it)
- trigger an inbox check (/data/triggers/checkInbox?token=...)
- check in DB, that the scale property of that dataset is still set
- try to download tracing

### Issues:
- #2316 (step 1)

------
- [x] Ready for review

### CODE REVIEW

**Comment by normanrz** [comment]
With this PR I still can't download tracings of deactivated tracings. `"error": "Couldn't find the requested resource."`. I updated the PR description for steps to test)

`scale` remains in dataset object tho.

**Comment by jfrohnhofen** [comment]
@norman keeping the scale is the only purpose of this PR. This is enough to be able to update the datasets and deploy the code (and fix the currently undeployable master). I am currently on a second PR to reenable the download, which should be done in a couple minutes, but I was originally not sure how long this would take; hence the two PRs

**Comment by normanrz** [comment]
ah ok. I missed that. Sorry!

**Comment by jfrohnhofen** [comment]
@normanrz the second "PR" is now finished as well, so I would suggest doing it all at once.

**Comment by jfrohnhofen** [comment]
So feel free to test the tracing download again, it should work now.

**Pull request merged**
