### PR TITLE
Make zoom value feel the same in all views and clean up arbitrary mode

### LINKED ISSUE #1829: Zoom value should feel the same for all tracing modes
Currently switching between ortho and flightmode with the same constant zoom value will result in one being zoomed in far more than the other.
This is most likely caused due to the 3D camera being closer to the plane the flight mode. Perhaps we can set up the scene identically for both tracing modes so that zoom feels the same.

See also: https://discuss.webknossos.org/t/zoom-is-combined-since-update/217

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1829/create?referer=github" target="_blank">Log Time</a>

### PR DESCRIPTION
**Pull request by daniel-wer**
What started as fixing the long-waiting issue #1829 evolved into cleaning up all sorts of things in the arbitrary views. I increased the texture size for the oblique and flight mode to that of the orthogonal mode and didn't experience any performance issues.
I repaired broken user settings: `sphericalCapRadius, crosshairSize and displayCrosshair`.
Scaling of the oblique and flight modes was not persisted before and there was a strange artifact if one of those modes was loaded as the very first mode. I've reused the scale of the orthogonal mode for those two modes and fixed the artifact. I've also removed some dead code.
Also before this PR the crosshair in arbitrary modes was rescaled by threejs in every frame as its texture size was not a power of 2, which resulted in lots of warnings in the console - fixed now.

### Mailable description of changes:
 - The zoom value in all views should now feel the same. The pixel density of the flight and oblique views has been increased. Scaling the flight or oblique view will now be persisted.

### Steps to test:
- Switch between the modes. Zoom in using `i, o`, scale using `k, l`. Zoom and scale should be the same in all modes. Test the user settings that I mentioned.

### Issues:
- fixes #1829

------
- [x] Ready for review

### CODE REVIEW

**Comment by hotzenklotz** [comment]
@daniel-wer Nice! How do I test the effect of the `sphericalCapRadius`? When I play around with the slider there is not much visible feedback.

**Comment by daniel-wer** [comment]
@hotzenklotz Rotate using the arrow keys, this makes the difference quite clear :)

**Comment by normanrz** [comment]
@daniel-wer Thanks for spending time on this!
When I look at ortho and oblique mode (with 0,0,0 rotation), they are not identical which I would have assumed. Seems like they are off be 1 or 2 slides.
bildschirmfoto 2017-10-26 um 16 02 34
bildschirmfoto 2017-10-26 um 16 02 31

**Comment by daniel-wer** [comment]
I just fixed another (actually quite bad) bug, that seems to have existed for a long time. Go onto master and set a node in orthogonal mode at a spot where it's easily locatable (e.g. inside a small cell). Now move the view using your mouse or the arrow keys. Observe how the nodes position in relation to the texture changes once it is moved further to the edge of the viewport ^^
That should no longer be the case, it was caused because at some places the `VIEWPORT_WIDTH` (witdh of the data plane + border size) was used instead of the `PLANE_WIDTH` (width of data plane only).

**Comment by daniel-wer** [comment]
I've had a look at all occurrences of `PLANE_WIDTH` and `VIEWPORT_WIDTH` and hopefully corrected all of those that were wrong.

**Comment by hotzenklotz** [comment]
@daniel-wer Either wait with merging for BNW or merge into BNW branch.

**Pull request merged**
