### PR TITLE
Remove sbt-style Versioning (obsolete next to CI build/tag versioning)

### LINKED ISSUE #2906: is the version file still needed, next to CI versioning?

### PR DESCRIPTION
**Pull request by fm3**
### URL of deployed dev instance (used for testing):
- https://removesbtversioning.webknossos.xyz

### Steps to test:
- CI should run through, should be deployable
- api/buildinfo should not feature `version` anymore, but should still be useful with `ciTag`/`ciBuild`
- Can you think of anything else that might break? @normanrz @jstriebel 

### Issues:
- fixes #2906

------
- ~~[ ] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)~~
- ~~[ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~~
- [x] Ready for review

### CODE REVIEW

**Comment by normanrz** [comment]
Does this affect the jars in any way?

**Comment by fm3** [comment]
Not that I know of, but I can’t be sure. Deploy on the dev server seems to have worked

**Comment by normanrz** [comment]
I did the comparison:

# OLD
```
│   ├── oxalis_2.11-2.0.2-javadoc.jar
│   ├── oxalis_2.11-2.0.2-sans-externalized.jar
│   ├── oxalis_2.11-2.0.2-sources.jar
│   ├── oxalis_2.11-2.0.2-web-assets.jar
│   ├── oxalis_2.11-2.0.2.jar
│   ├── oxalis_2.11-2.0.2.pom
│   │   ├── oxalis
│   │   │   └── oxalis_2.11
│   │       ├── oxalis-oxalis_2.11-compile-internal.xml
│   │       ├── oxalis-oxalis_2.11-compile.xml
│   │       ├── oxalis-oxalis_2.11-docs.xml
│   │       ├── oxalis-oxalis_2.11-optional.xml
│   │       ├── oxalis-oxalis_2.11-plugin.xml
│   │       ├── oxalis-oxalis_2.11-pom.xml
│   │       ├── oxalis-oxalis_2.11-protobuf.xml
│   │       ├── oxalis-oxalis_2.11-provided.xml
│   │       ├── oxalis-oxalis_2.11-runtime-internal.xml
│   │       ├── oxalis-oxalis_2.11-runtime.xml
│   │       ├── oxalis-oxalis_2.11-scala-tool.xml
│   │       ├── oxalis-oxalis_2.11-sources.xml
│   │       ├── oxalis-oxalis_2.11-test-internal.xml
│   │       └── oxalis-oxalis_2.11-test.xml
│   │   │   ├── oxalis
│   │   │   └── oxalis.bat
│   │   │   ├── oxalis.oxalis-2.0.2-assets.jar
│   │   │   ├── oxalis.oxalis-2.0.2-sans-externalized.jar
```
# NEW
```
│   ├── oxalis_2.11-0.1-SNAPSHOT-javadoc.jar
│   ├── oxalis_2.11-0.1-SNAPSHOT-sans-externalized.jar
│   ├── oxalis_2.11-0.1-SNAPSHOT-sources.jar
│   ├── oxalis_2.11-0.1-SNAPSHOT-web-assets.jar
│   ├── oxalis_2.11-0.1-SNAPSHOT.jar
│   ├── oxalis_2.11-0.1-SNAPSHOT.pom
│   │   ├── oxalis
│   │   │   └── oxalis_2.11
│   │       ├── oxalis-oxalis_2.11-compile-internal.xml
│   │       ├── oxalis-oxalis_2.11-compile.xml
│   │       ├── oxalis-oxalis_2.11-docs.xml
│   │       ├── oxalis-oxalis_2.11-optional.xml
│   │       ├── oxalis-oxalis_2.11-plugin.xml
│   │       ├── oxalis-oxalis_2.11-pom.xml
│   │       ├── oxalis-oxalis_2.11-protobuf.xml
│   │       ├── oxalis-oxalis_2.11-provided.xml
│   │       ├── oxalis-oxalis_2.11-runtime-internal.xml
│   │       ├── oxalis-oxalis_2.11-runtime.xml
│   │       ├── oxalis-oxalis_2.11-scala-tool.xml
│   │       ├── oxalis-oxalis_2.11-sources.xml
│   │       ├── oxalis-oxalis_2.11-test-internal.xml
│   │       └── oxalis-oxalis_2.11-test.xml
│   │   │   ├── oxalis
│   │   │   └── oxalis.bat
│   │   │   ├── oxalis.oxalis-0.1-SNAPSHOT-assets.jar
│   │   │   ├── oxalis.oxalis-0.1-SNAPSHOT-sans-externalized.jar
```

**Comment by normanrz** [comment]
I don't understand where `2.11` is coming from. Maybe we can replace `2.11-0.1-SNAPSHOT` with `18.7-SNAPSHOT` or something? But only cosmetics.

**Comment by fm3** [comment]
`2.11` is the scala version. I changed `0.1-SNAPSHOT` to `wk` in order to keep the names clutter-free, does that work for you?

**Pull request merged**
