### PR TITLE
Ensure a warning is shown when segmentation is disappearing due to layout changes

### LINKED ISSUE #4181: Ensure a warning is shown when segmentation is disappearing due to layout changes
See #4173.

### PR DESCRIPTION
**Pull request by daniel-wer**
Also fixed that the warning was not displayed immediately when loading the tracing.

### URL of deployed dev instance (used for testing):
- https://showsegmentationwarning.webknossos.xyz

### Steps to test:
- Open a volume tracing with existing segmentation. Zoom out so the segmentation is not displayed. Reload the page - the warning should be displayed without having to zoom first.
- Open a volume tracing with existing segmentation. Zoom out so you are at the edge of the segmentation disappearing (you should see the segmentation). Now enlarge the data viewports until the segmentation disappears (due to the active resolution changing) - the warning should be displayed.

### Issues:
- fixes #4181 

------
- ~~[ ] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)~~
- [x] Ready for review

### CODE REVIEW

**Comment by daniel-wer** [comment]
> Unfortunately, it didn't work perfectly for me. When I open a tracing at a zoom level where the warning should be shown, it is shown for only a split second (the toast hides immediately).

This is due to the initialization lag :/ Unfortunately, I don't really see a better option than waiting a little after receiving the `WK_READY` event to circumvent this. That's not a very reliable fix, though...

**Comment by philippotto** [comment]
> > Unfortunately, it didn't work perfectly for me. When I open a tracing at a zoom level where the warning should be shown, it is shown for only a split second (the toast hides immediately).
> 
> This is due to the initialization lag :/ Unfortunately, I don't really see a better option than waiting a little after receiving the `WK_READY` event to circumvent this. That's not a very reliable fix, though...

Hmm, bummer. But a `sleep` sounds fine (could be even something like 5s?). That would fix it most of the time, right?

**Comment by daniel-wer** [comment]
Yes, that should fix it most of the time - added the sleep.

**Comment by daniel-wer** [comment]
@philippotto Can you test again and/or approve? :)

**Pull request merged**
