### PR TITLE
refuse tracing update actions for finished annotations

### PR DESCRIPTION
**Pull request by fm3**
### Steps to test:
- open annotation in a tab, in another, keep the dashboard
- in dashboad, finish the annotation
- updates to the annotation should be refused (triggered reload shows read-only mode)

------
- [x] Ready for review

### CODE REVIEW

**Comment by fm3** [comment]
this is *also* checked in the write-access check, but since that one is cached, it does register short-term changes like finishing the annotation. @jfrohnhofen do you think we could remove this caching for all write-access checks? or should we *only* check the isFinished property like I do in this PR, and not at all in the write-access check?

**Comment by jfrohnhofen** [comment]
Where does the write-access check occur? And where is it cached usually?

**Comment by fm3** [comment]
I’m talking about the `TokenSecuredAction`s in the datastore (see [`TracingController`](https://github.com/scalableminds/braingames-libs/blob/master/braingames-datastore/app/com/scalableminds/braingames/datastore/controllers/TracingController.scala#L107), which in turn lead to [`hasUserAccess`](https://github.com/scalableminds/braingames-libs/blob/master/braingames-datastore/app/com/scalableminds/braingames/datastore/services/AccessTokenService.scala#L63)

**Comment by jfrohnhofen** [comment]
I would favor leaving in both checks, since they check for (slightly) different things. The token based check is used to ensure authorized access (who is allowed to do what), the `isFinished` check is part of business logic / the behavior of annotations. But these are two different concerns imo and should thus not be mixed up / replace one another. The caching should only affect the message displayed, but not the behavior!? Is showing different messages a problem?

**Comment by hotzenklotz** [comment]
@fm3 What's the status here?

**Comment by fm3** [comment]
yeah we can merge it and open another one for removing the redundancy and avoiding cache-caused delay on *unfinishing*

**Pull request merged**
