### PR TITLE
Allow base layer name as new volume layer name

### PR DESCRIPTION
**Pull request by Dagobert42**
### Steps to test:
- create new volume layer based on segmentation layer and name it segmentation layer

------
- [x] Ready for review

### CODE REVIEW

**Comment by Dagobert42** [comment]
It looks like we only call this through the add volume layer modal. Is that correct?

**Review by philippotto — APPROVED** [review]
great! changes look good and testing also showed that this works :+1: 

please wait with merging until monday, though :)

**Comment by philippotto** [comment]
> It looks like we only call this through the add volume layer modal. Is that correct?

The code you changed is within `AddVolumeLayerModal` and only used for the modal. `validateReadableLayerName` itself is also used when renaming an existing layer, but there's no need to change anything there.

**Comment by normanrz** [comment]
This does not fix #6238, does it?

**Comment by philippotto** [comment]
> This does not fix #6238, does it?

You're right, this is independent of each other.

**Pull request merged**
