### PR TITLE
fix "cancel task" message

### PR DESCRIPTION
**Pull request by hotzenklotz**
### Mailable description of changes:
 - [Dashboard.Tasks] Changed task canceling confirmation message to say "cancel" instead of "delete"

### Steps to test:
- Get a task
- Cancel the task. Confirmation modal should read "cancel" instead of "delete".

### Issues:
- fixes https://discuss.webknossos.org/t/delete-annotation/593

------
- [ ] Ready for review

### CODE REVIEW

**Comment by daniel-wer** [comment]
I think you "fixed" the wrong message. Heiko complained about the "Do you really want to delete this annotation?" message that appears in the task list view, if you display all annotations for one task. Then select "Cancel" in the Actions dropdown and the wrong message is shown.

**Comment by daniel-wer** [comment]
Also what exactly does cancel do for tasks and annotations? Is it really only a cancel for both tasks and annotations. If it's a delete instead, it should also be called delete.
I just want to make sure, the naming is correct and everybody understands what happens if you press "Cancel".

**Comment by hotzenklotz** [comment]
@daniel-wer Thanks for being so vigilant. I think I got confused there myself for a second. I believe the correct messages should be shown now.

Regarding your second question: From a technical perspective there is no difference between "delete" and "cancel". The annotation will be removed aka deleted. Heiko explicitly prefers the term "cancel" to indicate that a user is not indeed deleting the whole task (aka the template for all task instances) but rather just a single annotation (aka a single task instance). This is done to encourage people to use this feature.

giphy

**Comment by daniel-wer** [comment]
Nice, merged, tested, lgtm :)

**Comment by hotzenklotz** [comment]
@daniel-wer Please approve. 
image

**Pull request merged**
