### PR TITLE
re-report datasource json on dataset reload trigger

### LINKED ISSUE #3734: “reload” button for single dataset should also re-report datasource properties to wK

### PR DESCRIPTION
**Pull request by fm3**
The frontend could directly use the returned datasource to update the values in the list. Also, I did not change the frontend code so there the functions are still called clearCache (for the record, the cache is still cleared, but the call _also_ reloads the datasource properties). ~~@daniel-wer @philippotto does one of you want to take this?~~

### URL of deployed dev instance (used for testing):
- https://reloaddatasource.webknossos.xyz

### Steps to test:
- change datasource properties on disk
- hit “reload” in wk dataset list
- new datasource properties should be reported to wK

### Issues:
- fixes #3734 

------
- ~~[ ] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)~~
- ~~[ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- [x] Needs datastore update after deployment
- [x] Ready for review

### CODE REVIEW

**Comment by daniel-wer** [comment]
> The frontend could directly use the returned datasource to update the values in the list.

This will be much easier to implement after I finished #3740, because I'll remove the publications tab from the dashboard, there, which will simplify the dataset fetching/handling.

I would say, it's still fine to merge this beforehand, or do you think this is a deal breaker?

**Comment by fm3** [comment]
Thanks for your reply! Then review and merge the back-end separately. Do you think it’s fine that the front-end functions are still called clearCache? I wasn’t sure how to clean up there.

**Comment by daniel-wer** [comment]
Yes that's fine, I'll rename those when I implement the frontend dataset update part of this (if I can think of a good name by then ^^).

**Comment by fm3** [comment]
Thanks!
It is different in that it is specific to a single (already present, and specified) dataset.

**Comment by jstriebel** [comment]
PS @fm3 : Is this endpoint part of the documented api? Maybe this should be updated or versioned then.

**Comment by fm3** [comment]
Good point, but so far the documented and versioned REST API was only in webKnossos, not the datastore, and I vote to keep it that way for now.

**Pull request merged**
