### PR TITLE
Update installation instructions for ubuntu 20.04

### LINKED ISSUE #5748: Update README to Ubuntu version 18.04 or 20.04
## Detailed Description
Currently, according to the README Ubuntu version 16.04 is required/supported. As this version is no longer supported, we should adjust the readme to a newer version.

### PR DESCRIPTION
**Pull request by MichaelBuessemeyer**
This PR edits the Installation section of the README. It updates the commands for the ubuntu installation to version 20.04.

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- Test the updated installation steps and look whether wk is running as expected.
- Also test whether the docker installation works.

### Issues:
- fixes #5748

------
- ~~[ ] Updated [(unreleased) changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)~~
- ~~[ ] Updated [(unreleased) migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes~~
- ~~[ ] Needs datastore update after deployment~~
- [x] Ready for review

### CODE REVIEW

**Comment by MichaelBuessemeyer** [comment]
@youri-k I assigned you, as you are the next person in the line to check the installation setup :)

@fm3 The backend seems to assume that the wk directory should be a git repo `backend: fatal: not a git repository (or any of the parent directories): .git`. Is this really necessary? I just used the Zip download and except for these warnings in the console, everything looks fine to me.
Second, it looks like the default `application.conf` settings configure wk in a way that it assumes that a wk worker should be running and thus leading to many failing requests in the backend. I suggest that we should maybe adjust the application.conf settings or at least add a config version where a worker is not expected.

**Comment by fm3** [comment]
Thanks for looking into this!

 - The “not a git repository” error is not critical (even though admittedly the logging suggests it…). The git commands are run by the webknossos backend to populate the api/buildinfo data. If they fail, some of the fields there will be empty, but that sould not be a huge problem for users who just want to try out wk. We could redirect the logging from git and add a pacifying message, but maybe that is a too-rare case to invest in :shrug: 
 - Are you certain that you had the current master of application.conf? It says `jobsEnabled = false` here currently https://github.com/scalableminds/webknossos/blob/master/conf/application.conf#L80 – but there may be parts of the code that do not check this properly. This should be investigated. Could you post the logging of those requests? Did they occur independent of the open pages? Did the front-end also show the jobs page link in the menu?

**Comment by MichaelBuessemeyer** [comment]
> Are you certain that you had the current master of application.conf?

The application.conf says: `jobsEnabled = false` and `isDemoInstance = false`. Thus the config should be fine.
The network tab in the dataset list dashboard shows that the frontend requests the jobs from time to time:
Screenshot from 2021-10-04 11-56-08
Thus I think the frontend is at fault here.

Nevertheless, I think if jobs are disabled in via the application.conf shouldn't each job related request trigger a 403 error code "Forbidden"?
Here is the error logged by the backend:
```
backend: 2021-10-04 11:56:30,983 [info] com.scalableminds.webknossos.datastore.services.DataSourceService - Finished scanning inbox (binaryData): 1 active, 0 inactive
backend: 2021-10-04 11:56:31,025 [info] controllers.WKRemoteDataStoreController - Received dataset list from datastore 'localhost': 1 active, 0 inactive datasets
backend: 2021-10-04 11:56:31,095 [debug] com.scalableminds.webknossos.datastore.rpc.RPCRequest - Sending WS request to http://localhost:8888/api/tasks?offset=0 (ID: 9). RequestBody: ''
backend: 2021-10-04 11:56:31,099 [error] com.scalableminds.webknossos.datastore.rpc.RPCRequest - Error sending WS request to http://localhost:8888/api/tasks?offset=0 (ID: 9): Connection refused: localhost/127.0.0.1:8888
backend: play.shaded.ahc.org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
backend:     play.shaded.ahc.org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
backend:     play.shaded.ahc.org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
backend:     play.shaded.ahc.org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
backend:     play.shaded.ahc.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
backend:     play.shaded.ahc.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
backend:     play.shaded.ahc.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
backend:     play.shaded.ahc.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
backend:     play.shaded.ahc.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
backend:     play.shaded.ahc.io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
backend:     play.shaded.ahc.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
backend:     play.shaded.ahc.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
backend:     play.shaded.ahc.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
backend:     play.shaded.ahc.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
backend:     play.shaded.ahc.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
backend:     play.shaded.ahc.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
backend:     play.shaded.ahc.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
backend:     play.shaded.ahc.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
backend:     play.shaded.ahc.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
backend:     play.shaded.ahc.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
backend:     java.lang.Thread.run(Thread.java:748)
backend: 2021-10-04 11:56:31,099 [warn] models.job.JobService - Could not update celery infos: Failure(Error sending WS request to http://localhost:8888/api/tasks?offset=0 (ID: 9): Connection refused: localhost/127.0.0.1:8888
backend: play.shaded.ahc.org.asynchttpclient.netty.channel.NettyConnectListener.onFailure(NettyConnectListener.java:179)
backend:     play.shaded.ahc.org.asynchttpclient.netty.channel.NettyChannelConnector$1.onFailure(NettyChannelConnector.java:108)
backend:     play.shaded.ahc.org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:28)
backend:     play.shaded.ahc.org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
backend:     play.shaded.ahc.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
backend:     play.shaded.ahc.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
backend:     play.shaded.ahc.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
backend:     play.shaded.ahc.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
backend:     play.shaded.ahc.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
backend:     play.shaded.ahc.io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
backend:     play.shaded.ahc.io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
backend:     play.shaded.ahc.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
backend:     play.shaded.ahc.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
backend:     play.shaded.ahc.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
backend:     play.shaded.ahc.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
backend:     play.shaded.ahc.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
backend:     play.shaded.ahc.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
backend:     play.shaded.ahc.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
backend:     play.shaded.ahc.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
backend:     play.shaded.ahc.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
backend:     java.lang.Thread.run(Thread.java:748),Empty,Empty)

```

**Comment by MichaelBuessemeyer** [comment]
> Thanks for going through this. I just added some wording suggestions slightly_smiling_face

Thanks a lot :smile_cat:

**Comment by philippotto** [comment]
This can be merged, right? :)

**Comment by youri-k** [comment]
Yes :slightly_smiling_face:

**Pull request merged**
