### PR TITLE
Move "User access list" to Settings

### LINKED ISSUE #6068: move dataset access list from dashboard to settings page
Dataset access list (“users with access rights”) is too prominent in the dashboard. Should be moved to dataset settings page

### PR DESCRIPTION
**Pull request by hotzenklotz**
PR does two little things:
- move the "Users with Access" list form the main Dashboard->My Datasets (sub)-table to the the settings (under "Sharing Tab") 
- renamed all the react components used in the dataset settings view to reflect that:
  - all components are some tab
  - all components belong to the dataset settings view

### URL of deployed dev instance (used for testing):
- https://useraccesslist.webknossos.xyz/

### Steps to test:
1. Navigate to Dashboard --> My Datasets
    -  Table should no longer be expandable to show "Users with access"
2. Go to Setting for a dataset --> "Sharing Tab"
3. Expand "Users with access" panel. 
4. Tada

### Issues:
- fixes #6068 

------
(Please delete unneeded items, merge only when none are left open)
- [x] Updated [(unreleased) changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [ ] Updated [(unreleased) migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Needs datastore update after deployment
- [x] Ready for review

### CODE REVIEW

**Review by philippotto — APPROVED** [review]
Awesome, great (and needed) clean up, too :+1: 

I'm wondering whether user might expect that the list "live updates" to changes which are not saved, yet? Maybe the text could clarify that this is not a preview? Not sure how, though, and maybe I'm overthinking this..

**Comment by hotzenklotz** [comment]
> I'm wondering whether user might expect that the list "live updates" to changes which are not saved, yet? Maybe the text could clarify that this is not a preview? Not sure how, though, and maybe I'm overthinking this..

I hadn't thought about that yet. Perhaps I add a little "i" icon with short description to clarify that.

**Comment by hotzenklotz** [comment]
@philippotto How about:
image

**Comment by philippotto** [comment]
> @philippotto How about: image

:+1:

**Pull request merged**
