### PR TITLE
adds y-axis scale to the histogram view

### LINKED ISSUE #4297: Add scale to y-axis of histogram

### PR DESCRIPTION
**Pull request by MichaelBuessemeyer**
### URL of deployed dev instance (used for testing):
- [dev-instance](https://addyscaletohistogram.webknossos.xyz/auth/login)

### Steps to test:
- open a tracing
- open the datasets tab in the settings
- the histogram should now have a scale at the y-axis indicating the logarithmic scale

### Issues:
- fixes #4297

------
- [x] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)
- ~~[ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes~~
- ~~[ ] Needs datastore update after deployment~~
- [x] Ready for review

### CODE REVIEW

**Comment by philippotto** [comment]
Thanks for adding this scale! However, I'd vote for a more visual approach (without specific numbers). The numbers don't add much value (since they depend on a lot of factors, such as sample size, and cannot really be interpreted).

Instead, I'd suggest to only draw some horizontal lines which indicate the logarithm. Similar to the following pattern, multiple horizontal lines could be directly drawn into the canvas in a light blue (or gray) tone.

image

You can draw the lines by dividing the range of the histogram values into n equally-sized intervals (e.g., if the histogram covers values 0 to 1000; you could divide it into the ranges 0-200, 200-400, 400-600, 600-800, 800-1000). For the upper values of each interval, you calculate it's height in the logarithmic scale and draw the line there. This should reproduce the logarithmic visual from the picture above.

**Comment by MichaelBuessemeyer** [comment]
Following your suggestion I could produce the following:

image

As there are almost only lines a the top of the axis, this does not look nice to me.

I reworked this a bit to make this look more appealing. Now due to numeric instability the histogram looks quite different:
image

my conclusion: either the histogram or the axis scale do not look so good.
Lets talk about this a bit.

**Comment by philippotto** [comment]
> I reworked this a bit to make this look more appealing. Now due to numeric instability the histogram looks quite different:

Why do you need to change the histogram itself? I would have thought, that you could simply divide the maximum value in 4 ranges and then you only have 3 lines on the axis. But let's talk about this in person!

**Comment by MichaelBuessemeyer** [comment]
> I just checked why there is a `>` comparison instead of `>=`. The reason is pretty simple: The logarithm of 0 equals - infinity. Therefore this check is correct. Maybe a comment would be helpful to clarify this :).

I am adding the comment in PR #4349

**Comment by MichaelBuessemeyer** [comment]
We agreed on the second version (2nd picture)

**Comment by MichaelBuessemeyer** [comment]
@philippotto Everything should be ready for your second review. Lets wait for the CI to deploy a dev instance :+1:

**Comment by MichaelBuessemeyer** [comment]
@philippotto I added the dev instance :)

**Comment by philippotto** [comment]
Awesome! Will review in a bit :)

@fm3 In https://github.com/scalableminds/webknossos/pull/4349#issuecomment-561173647 it seems as if the normalization and logarithmic transformation helps to bring out a two-gaussian-characteristic. Maybe this insight helps when performing a histogram normalization? Not sure, whether this is helpful, but it just crossed my mind.

**Pull request merged**
