### PR TITLE
Refactor model part 2

### PR DESCRIPTION
**Pull request by daniel-wer**
This PR only serves as a review base to the first model refactoring PRs, to allow for combined testing. Once the testing was successful, this should be merged as quickly as possible.

No code review is needed, only testing!

This PR will include the PRs: #2681, #2687, #2664, #2733 

### URL of deployed dev instance (used for testing):
- https://refactormodelbase.webknossos.xyz/

### Steps to test:
- Test data loading and labeling (#2681)
- Test data loading (#2687)
- Test data rendering in all constellations (#2664)
- Test segmentation rendering of cells with id 0 (#2733)

### Issues:
- part of #2601

------
- [x] Ready for review

### CODE REVIEW

**Comment by philippotto** [comment]
@fm3 @daniel-wer  Do you know why this PR has conflicts in Global.scala? :see_no_evil:

**Comment by philippotto** [comment]
Cool, thank you!

**Comment by daniel-wer** [comment]
Alright, I've gone through the testing protocol (skeleton and volume tracing sections) and also did some freestyle testing, these are the things I noticed:

  - [ ] Create a volume tracing (with new segmentation), brush a bit, then download the tracing. Upload the zip-File again. Suddenly the tracing contains parts of the original segmentation again (although it was created using "new segmentation"). Maybe @fm3 knows sth about this? :)
  - [ ] Cells that have an id that is a multiple of 256 have no color (they look like id 0)
  - [ ] It is not possible to delete parts of an existing segmentation using right-click + trace or right-click + brush (open a volume tracing and select "existing segmentation"). However, if you brush over the existing segmentation, then the segmentation can be deleted. This feels strange.

1 and 3 exist on master as well, however, issue 2 is specific to this PR and should definitely be fixed!

For reference, the testing protocol (I added some sections and updated parts where appropriate):
https://docs.google.com/spreadsheets/d/1Y7n-fvnwjzRizHyQgftmj-p16h5wtajJ9A1EcX6eHks/edit#gid=1908350410

**Comment by philippotto** [comment]
Thanks for going through the testing protocol :+1: I think 3) is by design. Afaik, you can only delete the active cell (which is why you could delete what you painted since that's the active cell id then). Can you confirm that?

Re 2): We already had this issue at some point -.- Must have slipped again. Should I have a look?

**Comment by daniel-wer** [comment]
:man_facepalming: Nevermind regarding 3, you're absolutely right :D

**Pull request merged**
