### PR TITLE
rename datastore application.conf to avoid wrong precedence

### LINKED ISSUE #2560: wrong application.conf is loaded (on some machines, local development only)
sbt/play on some machines decides to load the application.conf of the datastore subproject even if the main webknossos project is launched. this leads to misbehavior.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2560/create?referer=github" target="_blank">Log Time</a>

### PR DESCRIPTION
**Pull request by fm3**
The deployments now need to specify that this renamed application.conf is to be loaded for standalone-datastores. (kube repo issue 144).
Also, the `docker-compose.yml` of the datastore is removed.

### Steps to test:
- wK should read correct application.conf on the machines where it previously didn’t

### Issues:
- fixes #2560

------
- [x] Ready for review

### CODE REVIEW

**Comment by fm3** [comment]
@jstriebel I guess we need to add the config file parameter also to `webknossos-datastore/docker-compose.yml` for it to pass the smoke test? Will that conflict with the deployment parameter?

**Comment by jstriebel** [comment]
@fm3 exactly. That should not conflict with the deployment, no.

**Comment by jstriebel** [comment]
@fm3 I just removed the unused sbt services for the datastore. The important part is to refer to the correct datastore in the Dockerfile.
Now we could even put the remaining docker-compose service into the main webknossos `docker-compose.yml`. Is it fine if I include that in this PR and hijack it?

**Comment by fm3** [comment]
fine by me

**Pull request merged**
