### PR TITLE
Optional usage of existing segmentation layer in hybrid tracings

### LINKED ISSUE #4022: Creating hybrid tracing should ask for new vs. existing segmentation
[Link to Discuss](https://discuss.webknossos.org/t/creating-hybrid-tracing-should-ask-for-new-vs-existing-segmentation/1444)

Similar to how it's done for "create volume tracing".

- [ ] create tracing button in view mode
- [ ] create hybrid tracing button in dashboard

### PR DESCRIPTION
**Pull request by MichaelBuessemeyer**
This PR makes it optional to use the existing segmentation layer for hybrid tracings. The behavior should be the same compared to volume tracings.

Please note the following trade-off I decided on: When viewing a dataset in view mode, it is possible to create a tracing from there on, but only if you are logged in. To not edit the login model that is displayed when the user clicks `Create Tracing` without being logged in, the tracing will only open up when selecting the button again after logging in. Keeping the dropdown open while the user uses the login model to log in, did not work out :confused: 

### URL of deployed dev instance (used for testing):
- [https://optionalreusageofsegmentationforhybrid.webknossos.xyz](https://optionalreusageofsegmentationforhybrid.webknossos.xyz)

### Steps to test:
- Logout, open a tracing in view mode and use the `Create  Tracing` Button.
- The login modal should open and ask you for logging in. Log in and use the `Create Tracing` button again. Now you should be able to select between using the existing segmentation layer or creating a new one. 
- Stay logged in and reopen any dataset in view mode. Now use the `Create Tracing` button again. The dropdown should now show up immediately and the creation of a tracing should work as usual.

- Open the dataset listing view in the dashboard (`Datasets`). From there open a hybrid tracing (explorational). The dropdown should be the same as for volume tracings and the creation should work as expected.

### Issues:
- fixes #4022

------
- [x] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)
- ~~[ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes~~
- ~~[ ] Needs datastore update after deployment~~
- [x] Ready for review

### CODE REVIEW

**Comment by philippotto** [comment]
> Please note the following trade-off I decided on: When viewing a dataset in view mode, it is possible to create a tracing from there on, but only if you are logged in. To not edit the login model that is displayed when the user clicks `Create Tracing` without being logged in, the tracing will only open up when selecting the button again after logging in. Keeping the dropdown open while the user uses the login model to log in, did not work out

Can't you show the dropdown for "with or without fallback layer" before the auth modal appears? You would probably need to store that information in the react state, so that `createTracing` can be called with the right arguments after auth was completed.

**Comment by MichaelBuessemeyer** [comment]
@philippotto I changed the behavior according to your suggestion. Could you please review the changes :)?

**Comment by philippotto** [comment]
Code looks good :+1: @MichaelBuessemeyer can you fix the CI and re-deploy the newest version on the dev server? Then I can test the code online :)

**Comment by philippotto** [comment]
I merged this since the lab pushed again for this :)

**Comment by MichaelBuessemeyer** [comment]
@philippotto Thanks a lot for taking care of this :tada: :slightly_smiling_face:

**Pull request merged**
