### PR TITLE
One Version per Transaction

### LINKED ISSUE #6495: Versions of volume data should be created at "transaction" points
Currently, editing volume data will create new versions where each version consists of at most 32 changed buckets (see `COMPRESSING_BATCH_SIZE`). However, this means that reverting to an older version might very well restore a state where chunk borders are visible since the version was created right in the middle of saving.
Ideally, the saving mechanism should use a transaction logic (similar to how it's done for skeletons) so that each version is a consistent tracing state.

An additional benefit of ditching the 32 limit is that we reduce the amount of versions being created (one large brush stroke can already cover much more than 32 buckets).

/edit: Another problem caused by this is that version conflicts (e.g., user B saved something while user A was saving larger changes) will result in missing data.

### PR DESCRIPTION
**Pull request by fm3**
Adapts the transaction management when saving updates to an annotation. Now, the version number is not increased inside of a transaction. The goal is a cleaner history, especially for volume annotations. Every version that shows up in the version history/restore view, should have a consistent state across mags, and complete brush strokes.

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- brush a high volume of data
- save
- look at version history and check that each version has consistent data

### TODOs:
- [x] Backend
  - [x] assume constant version for all groups of a transactions
  - [x] no longer assert increasing versions inside of a transaction
  - [x] instead assert increasing versions compared to the latest committed transaction
  - [x] also assert that the transactionGroupIndex is increasing monotonically when storing uncommitted update groups for a transaction
  - [x] transaction info is no longer optional in an update group, the frontend always sends this
  - [x] store uncommitted updates for more than 20 minutes, what if the user is offline for that time?
- [x] Frontend
  - [x] send constant version number for all groups of a transaction

### Issues:
- fixes #6495

------
- [x] Updated [changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [x] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)

### CODE REVIEW

**Comment by fm3** [comment]
Well possible that something’s wrong in the backend. I did this pretty quickly this afternoon. I can have a closer look on monday, or maybe we can debug together

**Comment by philippotto** [comment]
I looked at it with a fresh mind and found a logic error in my approach. However, the new code still runs into 409 errors. It's probably best to debug this together :) Maybe I misunderstand the new protocol. For the record, this is what the front-end is currently sending when brushing a single voxel:

```
[
  {version: 64, transactionId: "aiauvz190a", transactionGroupCount: 2, transactionGroupIndex: 0,…},
  {version: 64, transactionId: "aiauvz190a", transactionGroupCount: 2, transactionGroupIndex: 1,…},
  {version: 65, transactionId: "u2p7dhx3mw", transactionGroupCount: 1, transactionGroupIndex: 0,…}
]
```

The previous version was at 63. The above request fails. the version numbers look correct to me, though.

**Comment by fm3** [comment]
@philippotto I think I found the problem, could you try again?

Before we merge this, the backend should do one more assertion (see checkbox above), which I will add in the coming days.

**Comment by philippotto** [comment]
> @philippotto I think I found the problem, could you try again?

Awesome, works for me :+1:

**Review by normanrz — APPROVED** [review]

**Comment by fm3** [comment]
I think before we merge this we need to think about the retry logic again. In the old backend code there was a »failUnlessAlreadyHandled« method which suggests that this is about silently ignoring retries of saved actions. We probably need something like that again :thinking:

**Comment by philippotto** [comment]
> The version list is still a bit noisy. From a user's pov, it is not clear what the difference between "updated segmentation" and "modified annotation" is. Also, I think it is confusing that updating the segment list is a separate action. Screenshot 2023-08-29 at 13 47 02

Yes, you are right. This is still not ideal, but at least the volume data should be consistent at all times now. I created a potential follow-up here: https://github.com/scalableminds/webknossos/issues/7300 (however, I see the priority far lower compared to the current PR).

@fm3 Shall we merge? :)

**Comment by fm3** [comment]
> @fm3 Shall we merge? :)

As stated above, I think I have to re-visit the backend part once more, with respect to the retry logic. I’ll let you know once I think I restored it.

**Comment by philippotto** [comment]
> > @fm3 Shall we merge? :)
> 
> As stated above, I think I have to re-visit the backend part once more, with respect to the retry logic. I’ll let you know once I think I restored it.

Oh, I missed your comment. Probably had the tab open for too long.. Makes sense what you wrote :+1:

**Comment by fm3** [comment]
@philippotto I re-added the logic to ignore retries of requests that were already handled in the backend. I tested this locally and it seems to work. However, as discussed in person, let’s show this code to more people before merging, in order to avoid any subtle mistakes in this important part of the code.

**Comment by fm3** [comment]
@philippotto I’m not sure how to resolve the conflicts in the changelog. Looks like you edited multiple lines, but it also looks like they are in master (released changelog) already? Could you have a quick look?

**Comment by philippotto** [comment]
> @philippotto I’m not sure how to resolve the conflicts in the changelog. Looks like you edited multiple lines, but it also looks like they are in master (released changelog) already? Could you have a quick look?

I resolved the conflicts now. This PR added three lines and the rest was moved to the released file by the most recent release pr.

**Comment by philippotto** [comment]
For the record: @MichaelBuessemeyer and I discussed the PR, too, so the front-end is now reviewed multiple times and should be good to go.

**Review by frcroth — APPROVED** [review]
Issue for race conditions?

**Comment by fm3** [comment]
Thanks for going through this with me :tada: I created this follow-up issue https://github.com/scalableminds/webknossos/issues/7307

**Pull request merged**
