### PR TITLE
Rename Sample User

### PR DESCRIPTION
**Pull request by fm3**
Renames development mode default user SCM Boy to Sample User < sample @ scm.io >. Hoping that the shorter email address leads to less typing and gender neutrality leads to less exclusion.

### URL of deployed dev instance (used for testing):
- https://sampleuser.webknossos.xyz

### Steps to test:
- Start normally, log in as sample @ scm.io default password »secret« (or the internal dev deployment password)

------
- [x] Ready for review

### CODE REVIEW

**Comment by fm3** [comment]
As english is not my first language I am unsure about this, but the word Sample may be a bit unusual here. We could also consider changing all the »Sample« usages to »Example«. What do you think? Anybody more familiar with the language?

**Comment by philippotto** [comment]
Kudos for picking this up :+1: 

> As english is not my first language I am unsure about this, but the word Sample may be a bit unusual here. We could also consider changing all the »Sample« usages to »Example«. What do you think?

I'm not sure either, but from experience with other software, I would say that the following are at least more common for the use case:
- test user
- dummy user
- default user

However, in the end, it's not too important in my opinion.

**Comment by normanrz** [comment]
I think "Sample" is fine

**Review by philippotto — APPROVED** [review]

**Comment by jstriebel** [comment]
Nice! We also need to change this in wk-libs with the new release, see https://github.com/scalableminds/webknossos-libs/search?q=secretScmBoyToken

**Pull request merged**
