### PR TITLE
Update style of login, signup views

### PR DESCRIPTION
**Pull request by hotzenklotz**
I updated the style of the login, signup, password reset, and change password pages as suggested by Albane. Mostly I just added a colorful, flashy background with some neurons. 

The included SVG is not the smallest images. About 280kb gzipped. I tried to "optimize" it with [SVGOmg](https://jakearchibald.github.io/svgomg/) but the savings were neglectable.

Tested with Chrome, Safari, Firefox.

image

image

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- Open all the 4 pages and check styling
- Use dev tools to try responsive styling
- Try dark mode

### Issues:
- None

------
(Please delete unneeded items, merge only when none are left open)
- [x] Updated [changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [ ] Updated [migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Removed dev-only changes like prints and application.conf edits
- [ ] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [ ] Needs datastore update after deployment

### CODE REVIEW

**Comment by fm3** [comment]
I tried my hand at optimizing the SVG for file size, got from 429kb down to 39kb uncompressed. It does not look exactly identical (how important is it that the left neuron has stronger lines than the left one? /cc @Albane-dlv 
Find it here (note that it will look all-white on the white github background)

background_neurons_drawn_optimized

**Comment by philippotto** [comment]
Awesome :+1: Looks very cool!

Regarding @fm3's optimized SVG: If we want a less pronounced version, we could apply a blur(1px) filter. However, I'm fine with the optimized version as is :+1: 

> password reset, and change password pages

When I navigated to these pages, my initial thought was that it feels like I'm in the "logged-out area" now. Not sure whether that's just me or whether this flashy-background-theme is usually associated with being logged out. Apart from that, these pages look incorrect with the dark theme. See here:

image

I'd be fine with not styling these pages, as they are not used frequently.

**Comment by fm3** [comment]
>  Regarding @fm3's optimized SVG: If we want a less pronounced version, we could apply a blur(1px) filter. 

Or just tweak the alpha values again. I chose a compromise between the left and right neuron. (In my version, they have to be identical, because one is just a transformed clone of the other, with the svg <use> tag)

**Comment by hotzenklotz** [comment]
> I agree with Philipp that it might be less confusing to skip the change-password page in this redesign 🤔

I reverted the design for that site.

**Review by philippotto — APPROVED** [review]
Really loving this :+1: :man_dancing:

**Pull request merged**
