### PR TITLE
Add cach-all route and delete various empty-actions

### LINKED ISSUE #2238: create catch-all route to replace various empty routes
<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2238/create?referer=github" target="_blank">Log Time</a>

### PR DESCRIPTION
**Pull request by jfrohnhofen**
### Mailable description of changes:
- N/A

### Steps to test:
- load wK and make sure, that frontend routing still works

### Issues:
- fixes #2238

------
- [x] Ready for review

### CODE REVIEW

**Comment by jfrohnhofen** [comment]
we may still have a look at the `/annotations` and `/datasets` routes, since most of those should go unter `/api` as well .

**Comment by normanrz** [comment]
i suppose these are the routes in question (did i miss some?):
```
GET           /user/tasks/request                                controllers.TaskController.request
GET           /user/tasks/peek                                   controllers.TaskController.peekNext(limit: Int ?= 10)

GET           /datasets/:dataSetName/view                        controllers.DataSetController.view(dataSetName: String)
GET           /datasets/:dataSetName/trace                       controllers.AnnotationController.createExplorational(dataSetName: String, typ: String, withFallback: Option[Boolean])

POST          /annotations/upload                                controllers.AnnotationIOController.upload
GET           /annotations/:typ/:id/duplicate                    controllers.AnnotationController.duplicate(typ: String, id: String)
POST          /annotations/:typ/:id/edit                         controllers.AnnotationController.editAnnotation(typ: String, id: String)

GET           /annotations/:typ/:id/finishAndRedirect            controllers.AnnotationController.finishWithRedirect(typ: String, id: String)
GET           /annotations/:typ/:id/finish                       controllers.AnnotationController.finish(typ: String, id: String)
POST          /annotations/:typ/finish                           controllers.AnnotationController.finishAll(typ: String)
GET           /annotations/:typ/:id/reopen                       controllers.AnnotationController.reopen(typ: String, id: String)
GET           /annotations/:typ/:id/reset                        controllers.AnnotationController.reset(typ: String, id: String)
GET           /annotations/:typ/:id/revert                       controllers.AnnotationController.revert(typ: String, id: String, version: Int)
POST          /annotations/:typ/:id/transfer                     controllers.AnnotationController.transfer(typ: String, id: String)

GET           /annotations/:typ/:id                              controllers.AnnotationController.empty(typ: String, id: String)
GET           /annotations/:typ/:id/readOnly                     controllers.AnnotationController.emptyReadOnly(typ: String, id: String)

GET           /annotations/:typ/:id/info                         controllers.AnnotationController.info(typ: String, id: String)
GET           /annotations/:typ/:id/readOnly/info                controllers.AnnotationController.infoReadOnly(typ: String, id: String)
DELETE        /annotations/:typ/:id                              controllers.AnnotationController.cancel(typ: String, id: String)
GET           /annotations/:typ/:id/merge/:mergedTyp/:mergedId   controllers.AnnotationController.merge(typ: String, id: String, mergedTyp: String, mergedId: String)
GET           /annotations/:typ/:id/download                     controllers.AnnotationIOController.download(typ: String, id: String)
```

We should make sure that all of these become proper API routes (i.e. no server-side views or redirects) and put them under the `/api` prefix. UI routing should only be handled by the frontend

**Comment by jfrohnhofen** [comment]
That are the ones. I already took care of the two `/user` routes. Some of the others still have server-side redirects atm plus I don't know which parts of the frontend I need to add the `/api/` prefix for, so I wanted to confer with some frontend ppl first.

**Comment by normanrz** [comment]
understood. perhaps we defer that to keep this PR small?

**Comment by jfrohnhofen** [comment]
sure

**Comment by normanrz** [comment]
I added a catch-all frontend view in 19b315503

**Comment by daniel-wer** [comment]
@jfrohnhofen In the future, please simply remove the `Mailable description of changes` paragraph if there are no relevant changes for the release notes :)

**Pull request merged**
