### PR TITLE
Toggle trees

### LINKED ISSUE #1411: Hide trees in arbitrary modes
Pressing the key `1` should hide all trees in the three data viewports.

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1411/create?referer=github" target="_blank">Log Time</a>

### LINKED ISSUE #1921: Allow to toggle visibility of each tree
<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/1921/create?referer=github" target="_blank">Log Time</a>

### PR DESCRIPTION
**Pull request by philippotto**
### Mailable description of changes
- The visibility of each tree in a tracing can now be toggled in the tree tab. Toggling trees via "1" and "2" still works and also works in the arbitrary modes now.

### Steps to test:
- ensure the toggling works via the checkboxes as well as the new buttons in the tree-view
- ensure that only toggling tree visibility and saving doesn't send anything to the server
- ensure that node picking (shift click) still works and won't select invisible nodes

### Issues:
- fixes #1921 
- fixes #1411

------
- [X] Ready for review

I also removed the warning when toggling visibility via the shortcuts, since I think that checkboxes make it more than clear when all trees are hidden.

### CODE REVIEW

**Comment by hotzenklotz** [comment]
@philippotto If `tree.isVisible` is a new permanent property then we most likely need a DB evolution script too.

**Comment by philippotto** [comment]
> @philippotto If tree.isVisible is a new permanent property then we most likely need a DB evolution script too.

This PR only implements the property on client side. This means the visibility is not saved across tracing reloads, but I think this is fine for now. If people wish to have the visibility setting persisted, we can still do this, but as you mentioned this requires a DB schema update and evolution etc.

**Comment by hotzenklotz** [comment]
@philippotto Ok. This makes sense. Good job 👍

**Comment by philippotto** [comment]
I incorporated your suggestions, thanks!

**Pull request merged**
