### PR TITLE
Add option to hide unmapped segments in segmentation tab

### LINKED ISSUE #4398: [Merger Mode] Add to toggle for hiding all unannotated segments
When in Merger Mode, it is sometime hard to see what is going on. Which segments did I already annotate and which still need work. 

It would be great to have a simple toggle to hide all segments that are not marked/affected by the merger mode (=which do not contain a node). Toggling between all segments and the annotated ones make it very easy to see wich areas require more work.

Related:
- ID mappings already have a `hideUnannotatedIDs` options. I assume, there might be a way to reuse this code/functionality for the feature
- Thinking larger: 
  -  Perhaps this feature need not be tied to merger mode directly. It could make sense to just always offer this toggle. Often, skeletons are used for marking segments (but not necessarily to connect them like in Merger Mode)
  - (Perhaps, this toggle is also interesting for volume annotations. Especially, if one is drawing over an existing segmentation, it might be nice to hide any segment not touched by the user in any way (=hide the Fallback layer?))

### PR DESCRIPTION
**Pull request by MichaelBuessemeyer**
This PR adds the option to hide unmapped segments to the segmentation tab. The option is only available if a mapping is active.

### URL of deployed dev instance (used for testing):
- https://hideunmappedsegmentsinmergermode.webknossos.xyz

### Steps to test:
- Open a skeleton tracing and select a mapping
- When the mapping is loaded, the option to hide unmapped segments should appear and work as expected.
- Now open another skeleton tracing and start the merger mode. Using the new option you should see only mapped segments by skeletons. The other segments should be hidden.

### Issues:
- partly fixes #4398

------
- [x] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)
- ~~[ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes~~
- ~~[ ] Needs datastore update after deployment~~
- [x] Ready for review

### CODE REVIEW

**Comment by philippotto** [comment]
The PR itself looks good, but I'm hesitant to add further shortcuts to WK unless really necessary. In this particular case, we probably want to add a checkbox (or switch button) to the UI, anyway (probably to the segmentation tab?). If we have that, we don't need the shortcut at all, right? In that case, we wouldn't need to touch the merger-mode code. Do you agree?

**Comment by MichaelBuessemeyer** [comment]
> Do you agree?

A general solution would be nice :+1: But I cannot think of an implementation without too much overhead. Let's talk about this :phone:

**Comment by MichaelBuessemeyer** [comment]
@philippotto I updated the whole branch and this PR. Could you please review it? I tried to keep the changes small :smile:

**Comment by daniel-wer** [comment]
Very excited for this feature - I just tested it and it's exactly what I was looking for! It'll allow us to check whether a dense evaluation box is actually annotated densely or whether segments were missed by the tracer, very helpful :tada:

**Comment by MichaelBuessemeyer** [comment]
@philippotto Could you please check the newest version? I implemented all your suggested improvements

**Comment by MichaelBuessemeyer** [comment]
@philippotto Apparently this PR is pretty important to @daniel-wer. 
Could you please review it soon or give the review to @daniel-wer? :smile:
I want to make this change available to @daniel-wer as soon as possible :rocket:

**Comment by MichaelBuessemeyer** [comment]
🕺

**Pull request merged**
