### PR TITLE
Add more information to the info tab

### LINKED ISSUE #4836: Show "resource" summary of tracing in info tab
The info tab could show:
- which layers exist (and how many are currently active)
- (segmentation) mapping summary (how many and which is active)
- meshes (count)
- trees+nodes (already done, but maybe the active id could also be shown?)

### PR DESCRIPTION
**Pull request by MichaelBuessemeyer**
### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- Open a few hybrid tracings. The info tab should display the following additional information:
> - which layers exist (and how many are currently active)
> - (segmentation) mapping summary (how many and which is active)
> - meshes (count)
> - trees+nodes (already done, but maybe the active id could also be shown?)
 

### Issues:
- fixes #4836

------
-  ~~[ ] Updated [(unreleased) changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)~~
I don't think it is necessary to tell the users. I think they just discovering the additional info in the tab is ok.
- ~~[ ] Updated [(unreleased) migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes~~
- ~~[ ] Needs datastore update after deployment~~
- [x] Ready for review

### CODE REVIEW

**Comment by MichaelBuessemeyer** [comment]
Hi @philippotto, I just finished this PR. 

Could you please check this PR and tell me what you think about the layout and the order of the added information? I made the whole thing dynamic using flexbox.

**Comment by philippotto** [comment]
> Hi @philippotto, I just finished this PR.
> 
> Could you please check this PR and tell me what you think about the layout and the order of the added information? I made the whole thing dynamic using flexbox.

I like the dynamic layout :+1: 

Just a small suggestion regarding the styling:

```
.info-tab-category-title {
    border-bottom: 1px solid #ebebeb;
    margin-bottom: 2px;
    font-weight: bold;
}
```

In general, I think, that the info tab is now quite full (a logical consequence from the issue description :laughing:). I started a conversation in our slack channel to discuss this, as I don't have a good idea how to make it more lightweight :)

**Comment by MichaelBuessemeyer** [comment]
I just pushed the first version of the new "layout" that could be worked with.

It should be sufficient as a prototype.

**Comment by MichaelBuessemeyer** [comment]
This should wait for the decisions / implementation of #4996

**Comment by philippotto** [comment]
Awesome, thank you!

@normanrz feel free to check out the deployed version at: https://moreinfoforinfotab.webknossos.xyz/annotations/Explorational/5fdca3da010000a500273a1f#4608,4608,512,0,2.000

Maybe you can consider this scene-graph-like approach when you create mock-ups for https://github.com/scalableminds/webknossos/issues/4996. Depending on what the final layout will look like, this PR might be a good iteration which could be merged before pulling off the whole layout restructuring. That way, we could get the users acquainted with the sceen-graph-concept first and later restructure the remaining UI parts accordingly. Not too sure about this, but worth a thought.

**Comment by MichaelBuessemeyer** [comment]
@philippotto @normanrz This is closable in favor of the new statusbar and the Panel content reorganization #5384 PR, isn't it?

**Comment by philippotto** [comment]
Yes, agree :+1:

**Pull request closed without merging**
