### PR TITLE
Only apply blur on enter/esc behaviour to vector inputs and tree/group name input

### PR DESCRIPTION
**Pull request by MichaelBuessemeyer**
This is a follow-up PR for [4141](https://github.com/scalableminds/webknossos/pull/4141). It disables "blur on esc/enter" behavior for unwanted input components. The components left with this behavior are input vectors and the name input for tree/ group names in the trees tab.

### URL of deployed dev instance (used for testing):
- [https://makevectorinputsblurable.webknossos.xyz](https://makevectorinputsblurable.webknossos.xyz)

### Steps to test:
- Open a tracing.
- Try to edit and add linebreaks to the description via pressing enter. this should work out.
- Edit the position and rotation vector input in e.g. flight mode. Try to blur it with esc and enter. This should also work out. Also try this behavior for the name input of trees/groups in the trees tab.

------
- ~~[ ] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)~~
- ~~[ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes~~
- ~~[ ] Needs datastore update after deployment~~
- [x] Ready for review

### CODE REVIEW

**Comment by daniel-wer** [comment]
@MichaelBuessemeyer If I understand it correctly, the issue is that `Enter` in a `TextArea` triggered the blurring as well, which shouldn't be the case. Wouldn't it make more sense then to only disable the enter blurring for TextAreas but leave it as default otherwise? (This would come with the benefit that `Esc` blurring would still work in TextAreas)

**Comment by MichaelBuessemeyer** [comment]
@daniel-wer I talked with norman about this issue. His idea is to leave the behavior optional so the component that uses the `InputComponent` can decide whether the "blur on esc/enter" should be enabled or not.
As this is like I coded it, I suggest that I look up every component that uses the `InputComponent` and decide whether the behavior should be enabled or not.
Does that sound ok to you?

**Comment by daniel-wer** [comment]
Fine with me as well :)

**Comment by MichaelBuessemeyer** [comment]
> @MichaelBuessemeyer If I understand it correctly, the issue is that Enter in a TextArea triggered the blurring as well, which shouldn't be the case. Wouldn't it make more sense then to only disable the enter blurring for TextAreas but leave it as default otherwise? (This would come with the benefit that Esc blurring would still work in TextAreas)

On second thought this approach makes more sense as there is only one case where this behavior should be disabled (for the modal). This would keep the esc behavior and it is still possible for the user to have multi-line comments. Additionally this way we reduce the complexity of the interface/props of the `InputComponent` and unify the behavior for textareas and non-textares. 

So I think I will change it the way you suggested. Thanks for comming up with this :+1:

**Pull request merged**
