### PR TITLE
Highlight commented nodes

### LINKED ISSUE #2217: Highlight active comments
From [discuss](https://discuss.webknossos.org/t/jump-to-comments-of-selected-tree/638)
> When a node is selected the trees list automatically scrolls to the corresponding tree.
> This is not the case for the (node) comments list. Could this be implemented here as well?

<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2217/create?referer=github" target="_blank">Log Time</a>

### PR DESCRIPTION
**Pull request by philippotto**
~(Still waiting for final feedback from the lab.)~

### Mailable description of changes:
 - Commented nodes are now highlighted in the different viewports. Each commented node is painted in white and receives an additional border in the usual node color.

### Steps to test:
- Open a skeleton tracing
- Create, remove comments
- Reload page to see if comments are correctly rendered on initial render

### Test instance
https://highlightcommentednodes.webknossos.xyz

### Issues:
- fixes #2217 

------
- [x] Ready for review

### CODE REVIEW

**Comment by daniel-wer** [comment]
The testing mostly went well, but I think I found a bug related to comment deletion/merging trees. I wanted to create a nice gif but my gif tool of choice (peek) failed me under Ubuntu 18.04 -.-

So:
- Create two trees with one comment each.
- Remove one comment.
- Merge the two trees using `Shift-Alt-Click`.
-> Two nodes are marked as if they have a comment (instead of only the one).

This also happened when I:
- Created a tree with comments.
- Removed the entire tree.
- Created a new tree and created some nodes.
-> Some of the nodes were automatically marked as if the had a comment.

**Comment by philippotto** [comment]
Thanks for testing so thoroughly :+1: There was some initialization missing which led to these errors (as buffers are re-used). Now, I cannot reproduce your issues. Feel free to re-test (as soon as CI allows it).

**Comment by daniel-wer** [comment]
Works very well now, perfect! :)

**Comment by philippotto** [comment]
Thanks for the fix regarding the shader editor ;)

**Pull request merged**
