### PR TITLE
Delete outdated start script

### PR DESCRIPTION
**Pull request by jstriebel**

### CODE REVIEW

**Comment by fm3** [comment]
@youri-k @rschwanhold @jstriebel how do you prefer to start wK locally? I find `./sbt -jvm-debug 5005 run` a bit hard to type, same as `docker-compose up dev`, so I created a local Makefile with shortcuts for those. Maybe that should replace this start script?

Also, the issue of the wrong `application.conf` being read is still bugging me, but the -D in the start script didn’t seem to help everyone anyway.

**Comment by rschwanhold** [comment]
What is the problem with the script?

**Comment by youri-k** [comment]
@fm3 Currently I start wK locally with `./sbt -jvm-debug 5005 run`...

**Comment by fm3** [comment]
@rschwanhold its orignial, now obsolete, purpose was to start mongo with wK (related to #2447 )

**Comment by fm3** [comment]
how do you feel about yarn start? (added this in my commit here)

**Pull request merged**
