### PR TITLE
Check that sent json fields are json objects

### LINKED ISSUE #3856: ensure that json objects in postgres database are not just escaped strings

### PR DESCRIPTION
**Pull request by youri-k**
### Steps to test:
- edit `TaskType Recommended Configuration`
- check pgadmin that the json field is a json object 

### Issues:
- fixes #3856 

------
- [x] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable
- [x] Ready for review

### CODE REVIEW

**Comment by daniel-wer** [comment]
I took care of the remainder of the frontend part and tested that the recommended config modal still works. 

@youri-k One thing I noticed is that the default user config mistakenly contained a `zoom` property which is not needed and causes some unwanted behavior in the frontend. I removed it and it would be cool if we could remove it from userConfigurations in production as well. Should be something like `update webknossos.users set userconfiguration = userconfiguration - 'zoom'`, can we add that to the migration?

Another thing I noticed is that when creating a new user, the default userconfiguration looks like this:
```
{"configuration": {"scale": 1, "moveValue": 300, "scaleValue": 0.05, "moveValue3d": 300, "rotateValue": 0.01, "particleSize": 5, "crosshairSize": 0.1, "keyboardDelay": 200, "newNodeNewTree": false, "renderComments": false, "sortCommentsAsc": true, "sortTreesByName": false, "clippingDistance": 50, "displayCrosshair": true, "isosurfaceBBsize": 1, "layoutScaleValue": 1, "mouseRotateValue": 0.004, "isosurfaceDisplay": false, "overrideNodeRadius": true, "sphericalCapRadius": 140, "tdViewDisplayPlanes": true, "isosurfaceResolution": 80, "dynamicSpaceDirection": true, "highlightCommentedNodes": false, "clippingDistanceArbitrary": 64}}
```
Notice that everything is inside an extra `configuration` object, which is unwanted. This actually causes the backend default userconfiguration to never be applied by the frontend, instead the frontend default configuration is chosen (probably broke at some point in the past). Can you have a look and fix that or should we remove this altogether?. If you don't need the default user configuration in the backend, I think we can actually remove it altogether or make it an empty object (the frontend has defaults anyways and the keys from both configs are not in sync, see for example isosurfaceBBSize?!). We could also think about removing that `configuration` property in the migration then as well. @fm3 Could you read that last paragraph? Any objections?

@philippotto Should be ready for review :)

**Comment by fm3** [comment]
@daniel-wer the backend provides a method `configurationOrDefaults` which is used when querying the user configuration. It takes the data from the database and combines it with the backend defaults. If this is no longer desired, we can certainly remove all of that and use the front-end defaults only. This all seems rather messy right now and could use some cleanup :) The back-end does not do anything else with this data.
Concerning the other evolutions, I’m not sure how easy it is to move items from the `configuration` object to the top level (though I agree it would be desirable), @youri-k has more experience with the postgres json tools, could you comment on that? Same goes for removing `zoom` in those cases.

**Comment by fm3** [comment]
@youri-k could you add the new schemaVersion to both schema and evolutions? other than that, the backend LGTM. Please coordinate with @daniel-wer if his suggested changes should be part of this PR or can be a separate one :)

**Comment by daniel-wer** [comment]
We can clean up the user configuration in a separate PR, but let's tackle that sooner rather than later :)

**Pull request merged**
