### PR TITLE
Second Try: Support other units than nm for datasets

### PR DESCRIPTION
**Pull request by fm3**
Second try for #7783 

Reverts scalableminds/webknossos#7896

### TODO
 - [x] ensure full api compatibility with old libs (zarr datasource-properties.json)
 - [x] fix frontend problems (short vs long unit)
 - ~~[ ] problems when inserting datasets into db? (initial data? also later?)~~
   - [x] Cannot reproduce anymore 
 - ~~[ ] Fix not being able to change the unit in the frontend and submit the dataet settings~~
   - [x] Unrelated -> See #7903

### CODE REVIEW

**Comment by MichaelBuessemeyer** [comment]
@philippotto Could you please check the commit [d44d84a](https://github.com/scalableminds/webknossos/pull/7899/commits/d44d84a292d6d78884b60c8110fc60744977082d) and [d44d84a](https://github.com/scalableminds/webknossos/pull/7899/commits/d44d84a292d6d78884b60c8110fc60744977082d)?

**Review by MichaelBuessemeyer — COMMENTED** [review]
Backend Code LGTM.

Should I also test this with e.g. wklibs?

**Comment by fm3** [comment]
> Should I also test this with e.g. wklibs?

I tested that the align_section worker job still works. It uses Dataset.open_remote and a couple of dataset related APIs. I think that’s already a good start, but if you are motivated, I’m not opposed to more testing 😅

**Review by philippotto — COMMENTED** [review]
didn't test yet, since the ci is not done yet, but the code looks good :+1:

**Comment by MichaelBuessemeyer** [comment]
> I tested that the align_section worker job still works. It uses Dataset.open_remote and a couple of dataset related APIs. I think that’s already a good start, but if you are motivated, I’m not opposed to more testing 😅

I just installed a dev instance and tested it a little. Annotation / Viewing works totally fine, but updating the datasets unit does not work in the dataset settings. The frontend validation disallows this. => I'll investigate this tomorrow.

**Comment by MichaelBuessemeyer** [comment]
> I just installed a dev instance and tested it a little. Annotation / Viewing works totally fine, but updating the datasets unit does not work in the dataset settings. The frontend validation disallows this. => I'll investigate this tomorrow.

Nvm. This is already a problem on the master and unrelated to these changes. #7903 should fix this bug

**Review by MichaelBuessemeyer — APPROVED** [review]
As the backend has been reviewed & tested and the frontend has also been checked, I'd say it's ready to go :)

**Pull request merged**
