### PR TITLE
Properly reserve dataset when putting datasource (addRemote)

### LINKED ISSUE #7199: Adding dataset in folder with rights while not having rights to organization root folder
When a user does not have access rights to the root folder of an organization but access to a different (sub)folder, they can upload a dataset (which is automatically in the root folder) but then not access it (or even complete the import procedure). (additional context: https://scm.slack.com/archives/C5AKLAV0B/p1689069626934229?thread_ts=1689064935.050179&cid=C5AKLAV0B)

## Expected Behavior
Two options to fix this:
	- Store folder directly on upload so that the dataset is not uploaded into the root directory (preferred)
	- Disallow uploading generally when a user does not have access rights to the root directory

## Steps to Reproduce the bug

1. As the admin user, create a directory and give acess to a non-admin user via team permission (the non-admin user does not have rights to upload in the root directory)
2. Make the non-admin user team manager
3. As the non-admin user, try to upload a dataset in that folder

### LINKED ISSUE #7211: Set uploader when adding a remote dataset
Uploaders of datasets were introduced in https://github.com/scalableminds/webknossos/pull/5097, however they are not set when adding a remote dataset. This would be nice before tackling #5147

### LINKED ISSUE #7215: Supply Target Folder when adding Remote Dataset
Starting in #7176 (still WIP as of this writing) the backend supports a `folderId` field for the add route called by the frontend in `storeRemoteDataset`. The frontend should use that (and show a folder selection menu just like in the upload view).

This way the normal folder rights management is also respected when storing remote datasets. Otherwise, the user can only add remote datasets when having write access to the root folder

Related: #7199

### PR DESCRIPTION
**Pull request by fm3**
Datastore now calls `reserveDataSourceUpload` when adding a datasource. This sets both uploader and folderId properly, as well as performs the correct write access checks.

(Note that this is a subset of #7176 as I expect that to be blocked for a while, but we should fix this bug. I copied the changes to the two backend source files from that PR)

### Steps to test:
- Add remote dataset as non-admin user, see that this works for folders you have write access for (and not for others)
- Check that the folder is set correctly. (Also, uploader should be set in db)

### TODOs:
- [x] Frontend: pass folderId to the put route *instead of* calling updatePartial afterwards.

### Issues:
- fixes #7215
- fixes #7211
- fixes #7199

------
- [x] Updated [changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [x] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [x] Needs datastore update after deployment

### CODE REVIEW

**Comment by fm3** [comment]
@philippotto thanks! This works well when hitting the add button while navigated to a folder. However, in the upload view, there is a dropdown for specifying the folder. This is missing in the add remote view. Do you think this can be unified? I think having the menu (or at least a note saying where the dataset will go) would be good for the usability.

**Comment by philippotto** [comment]
> @philippotto thanks! This works well when hitting the add button while navigated to a folder. However, in the upload view, there is a dropdown for specifying the folder. This is missing in the add remote view. Do you think this can be unified? I think having the menu (or at least a note saying where the dataset will go) would be good for the usability.

Maybe I'm missing something, but the add-remote-view has the dropdown you want. However, it only appears after one has explored the first URI. I can see why showing it earlier might make sense, but due to the current explore-configure flow, the UI appears later. Changing that would take some effort which isn't worth it in my opinion.

image

**Comment by fm3** [comment]
I see, thanks! I missed it :see_no_evil: Yes, let’s keep it like that for now, then :)

**Review by frcroth — APPROVED** [review]
Very efficient! Closing 3 issues with one PR

**Pull request merged**
