### PR TITLE
Improve NML validation speed

### LINKED ISSUE #2241: improve NML validation performance
<a href="https://timer.scm.io/repos/537237ce1a00001a003c4a14/issues/2241/create?referer=github" target="_blank">Log Time</a>

### PR DESCRIPTION
**Pull request by jfrohnhofen**
### Mailable description of changes:
 - improved the NML-validation performance

### Steps to test:
- upload invalid NMLs (missing nodes, duplicate IDs, multiple tree components)

### Issues:
- fixes #2241

------
- [x] Ready for review

### CODE REVIEW

**Comment by hotzenklotz** [comment]
How much is the ~~fish~~ time improvement?

**Comment by jfrohnhofen** [comment]
before: ```checkForDuplicateIds took 48ms
allNodesInEdgesExist took 92139ms
nodesAreInEdges took 37367ms
checkTreesAreConnected took 227064ms```

after: ```checkNoDuplicateTreeIds took 1ms
checkNoDuplicateNodeIds took 98ms
checkAllNodesUsedInEdgesExist took 218ms
checkTreesAreConnected took 207ms```

**Comment by hotzenklotz** [comment]
Sweet :-D

**Comment by jfrohnhofen** [comment]
Yes, since that is captured by the "all trees are connected" check. If there are > 1 nodes and one node is not connected, the tree is not fully connected.

**Comment by daniel-wer** [comment]
When @jfrohnhofen comes to solve a problem :D

image

Great job!

**Comment by fm3** [comment]
That is quite an impressive improvement! I also like the coding style using Boxes of Unit instead of passing around the trees all the time.

I would suggest renaming `NMLValidator` to `SkeletonTracingValidator` or `TreeValidator` since it operates on the protobuf-generated datastructures, which is independent from the NML format. The `NmlParser` just happens to be the place that calls this, currently. Then we should possibly also move it to the libs? Maybe next to `TreeUtils`?

**Pull request merged**
