### PR TITLE
Update to React 18

### LINKED ISSUE #5795: Update React to v18
The profiling dev tools in chrome stopped working for me. Probably, a good incentive to update react and reduce the technical debt a bit.

- [React 18 Upgrade Guide](https://react.dev/blog/2022/03/08/react-18-upgrade-guide)

## ToDos
- [ ] ~~Fix `enzyme` component testing environment. Enzyme is not officially compatible with React 18~~
  - Idea 1: Maybe simple online fix?: https://www.npmjs.com/package/@cfaester/enzyme-adapter-react-18
  - Idea 2: Refactor tests in `react-testing-framework`. Maybe use copliot for that? https://testing-library.com/docs/react-testing-library/migrate-from-enzyme/
 - [x] Replace `ReactDOM.render` with `createRoot`
 - [x] Update dependencies as needed
   - [x] `antd` >=5.17.4
   - [x] `redux`
   - [x] `react-router`
   - [x] and many others. See PR for full list

### PR DESCRIPTION
**Pull request by hotzenklotz**
Update React to v18 and bump other libs as needed.

Dependency upgrades:
### `react`
- upgraded to from `17.0.x` to [`18.3.1` (latest / April 26, 2024)](https://github.com/facebook/react/releases/tag/v18.3.1)
- version `18.3.x` is the latest version before React
- upgraded corresponding Typesscript types
- [Upgrade guide](https://react.dev/blog/2022/03/08/react-18-upgrade-guide)

### `react-router-dom`
- upgrade from `5.1.x` --> `5.3.4`
- `5.3.3` is [mentioned as compatible with React 18](https://stackoverflow.com/questions/76096211/can-react-18-work-well-with-react-redux-and-react-router)
- this is last version of the `5.x`-branch before the complete react-router redesign/reconfig/crazyiness in v6
- no changelog available only [release notes](https://github.com/remix-run/react-router/releases/tag/v5.3.4)

### `redux` & `react-redux`
-  Upgraded `react-redux` from `7.1.x` --> `8.0.x`. 
    - [Changelog](https://github.com/reduxjs/react-redux/releases/tag/v8.0.0) list v8+ as React 18 compatible 
    - "Our performance benchmarks show parity with React-Redux v7.2.5 for both connect and useSelector, so we do not anticipate any meaningful performance regressions."
    - complete rewrite in Typescript
- upgraded `redux` from `3.6.0` to `4.1.2`
    - `react-redux` v8 requires requires redux 4.x
    - [`4.0.0` Changelog](https://github.com/reduxjs/redux/releases?expanded=true&page=2&q=v4) mentions very little issues: "If you're a React user, this is going to be a lot like going from 15 to 16. Not a lot of user-facing changes, but some interesting improvements under the hood."
    - [`4.1.0` Changelog](https://github.com/reduxjs/redux/releases/tag/v4.1.0) mentions mostly smaller bundle sizes
    - version `4.2.` starts deprecating "regular" redux in favor for `redux-toolkit` and in preparation for version 5. 

### `antd`
- upgraded from `5.16.x` to `5.17.4`
- 5.17.4 mentions several compatibility fixes for the depreacted React `findDomNode` API in [Changelog](https://ant.design/changelog#5174)

### `react-virtualized`
- replaced `react-virtualized` by [`react-virtualized-auto-sizer`](https://github.com/bvaughn/react-virtualized-auto-sizer) from the same author
- the lib is a newer standalone, smaller, TS-version of `<AutoSizer>` component

### `react-sortable-hoc` / `dnd-kit`
- replace deprecated, incompatible `react-sortable-hoc` with `dnd-kit`

### `react-debounce-render`
- No update available. left unchanged.
- Lib has not updated peer dependencies yet. [Open, stale Issue for React 18 support](https://github.com/podefr/react-debounce-render/issues/42)
- Only used `mappings_settings.tsx` component, so not very critical if we want to refactor

### `@tanstack/query`
- upgraded from `4.14.1` to `4.36.1`, latest v4-version before v5

### `flexlayout-react`
- upgrade from `0.5.5` to `0.7.15`(latest)
- [Changelog](https://github.com/caplin/FlexLayout/blob/master/ChangeLog.txt) indicates that version `0.7.x` brings React 18 support

### `react-json-tree`
- upgraded from `0.17.0` --> `0.19.0`
- while already compatible with React 18, React reported several deprecation warnings, e.g. `Support for defaultProps will be removed`. According to [Changelog](https://github.com/reduxjs/redux-devtools/blob/main/packages/react-json-tree/CHANGELOG.md) these were fixed in version 0.18 and 0.19

### URL of deployed dev instance (used for testing):
- https://react.webknossos.xyz/

### Steps to test:
- Try out dev deployment
- Run Typecheck

### TODOs:
- [x] Try `react-redux` v8.1.x
- [x] Try `redux` v4.1

### Issues:
- fixes #5795 

------
(Please delete unneeded items, merge only when none are left open)
- [x] Updated [changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [ ] Updated [migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Removed dev-only changes like prints and application.conf edits
- [x] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [ ] Needs datastore update after deployment

### CODE REVIEW

**Comment by hotzenklotz** [comment]
Screenshot 2024-09-04 at 17 26 38

There is still a React API deprecation warning for `ReactDom.findDomNode` which is caused by `antd`, more specially `resize-observer` & `rc-component/util`. The issues there have been open for quite some time now :-/ 
Not sure what to do.

See https://github.com/react-component/resize-observer/issues/208

**Review by philippotto — COMMENTED** [review]
Looks great :+1: 

I only found one thing during testing:

- [ ] the drag marker is not visible in dark mode

image

**Comment by philippotto** [comment]
> There is still a React API deprecation warning for ReactDom.findDomNode which is caused by antd, more specially resize-observer & rc-component/util. The issues there have been open for quite some time now :-/

I think, going ahead with this PR and hoping for a fix in the future is acceptable.

**Comment by hotzenklotz** [comment]
> Looks great 👍
> 
> I only found one thing during testing:

Great find. This is already the case on `master` 😶‍🌫️ I included a fix.

**Review by philippotto — APPROVED** [review]
upgrade

**Pull request merged**
