### PR TITLE
Rescale layers for different voxel sizes on remote import

### LINKED ISSUE #6821: Support adding multiple layers with different voxel sizes separately
When exploring [storage.googleapis.com/neuroglancer-fafb-data/fafb_v14/fafb_v14_orig](https://storage.googleapis.com/neuroglancer-fafb-data/fafb_v14/fafb_v14_orig/) with voxel size 4,4,40 and then adding [storage.googleapis.com/neuroglancer-fafb-data/fafb_v14/fafb_v14_clahe](https://storage.googleapis.com/neuroglancer-fafb-data/fafb_v14/fafb_v14_clahe/) with voxel size 8,8,40 a warning occurs and the resulting data is messed up. What should happen is that on the second dataset, the mags are adjusted so that it starts at mag 2,2,1. 

#6670 already implemented this when exploring a data source with multiple layers of different voxel sizes (e.g. segmentation and image), however this does not work when adding one layer and then adding and exploring another layer.

### PR DESCRIPTION
**Pull request by frcroth**
### URL of deployed dev instance (used for testing):
- https://differentvoxelsizes.webknossos.xyz

### Steps to test:
- See #6821 (add color, then add clahe as another layer -> notice that they are aligned in the resulting dataset)

### To-dos:
- [x] Frontend @philippotto 

### Issues:
- fixes #6821 

------
(Please delete unneeded items, merge only when none are left open)
- [x] Updated [changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [x] Needs datastore update after deployment

### CODE REVIEW

**Comment by philippotto** [comment]
@frcroth I just pushed the necessary frontend changes. let me know if you need anything else :mailbox:

**Comment by frcroth** [comment]
@philippotto 

There is still the warning:
```

**Comment by frcroth** [comment]
@philippotto 
Not sure what the problem is right now. You can also test it for the two layers in the issue. The backend gets the preferred voxel size correctly and returns a datasource with a coordinate transformation, but it does not seem to affect the frontend, so the datasource configuration does not include a coordinate transformation.

**Comment by philippotto** [comment]
> @philippotto Not sure what the problem is right now. You can also test it for the two layers in the issue. The backend gets the preferred voxel size correctly and returns a datasource with a coordinate transformation, but it does not seem to affect the frontend, so the datasource configuration does not include a coordinate transformation.

If I see it correctly, the backend defines the coordinate transformations once for the entire datasource. However, the transformations should be defined per layer. For example, if there are two layers (with differing voxel sizes), the first shouldn't have a transformation, but the second should get one so that it matches the 1st. Does this make sense?

**Comment by frcroth** [comment]
@philippotto Yes, thank you, your comment helped me and now it works :tada:

**Review by fm3 — COMMENTED** [review]
Backend looking good, just left two cosmetic suggestions.

As I mentioned before, this variant is not going to be able to register situations where e.g. the segmentation exists only starting at mag2 (but theoretically has the same voxel size). With this, it will register both starting at their individual mag1 with a transformation. In that particular case, my guess is that we would prefer calling it mag2, and have a uniform voxel size. However, I don’t know how to properly distinguish which case we want, with the limited information we are getting.

@philippotto Do you have an idea how this distinction could be made? I guess we could look for power-of-two divisibility, but that may yield false positives.

Otherwise, I’d say it is fine as is. One could also argue it is more correct to always call the “finest” existing mag of a layer mag1.

**Comment by philippotto** [comment]
> @philippotto Do you have an idea how this distinction could be made? I guess we could look for power-of-two divisibility, but that may yield false positives.

I've thought a bit about this and think that this is a pretty good heuristic. In the rare event of a false positive, the rendering should still be fine. Enumerating the mags differently could still be seen as a plausible way of bringing two layers together, in my opinion.

**Review by fm3 — COMMENTED** [review]
If I read the code correctly, the rounding of minVoxelSize/preferredVoxelSize the could be a problem. If one layer has 2.3 times the other’s voxel size, this might be wrongly detected as mag2, right? I think the isPowerOfTwo check has to be done on the doubles there, possibly with epsilon comparison.

Apart fromt hat, it looks good to me now :)

**Review by fm3 — APPROVED** [review]
Yes, perfect!

**Pull request merged**
