### PR TITLE
Add drag&drop nml upload functionality to dashboard

### LINKED ISSUE #2926: Allow d'n'd upload of NMLs in dashboard

### LINKED ISSUE #2972: Upload of multiple NMLs in dashboard should allow auto-creation of groups
Depends on #2926.

Feature request: https://discuss.webknossos.org/t/drag-and-drop-import-of-multiple-nml-files/1021/2?u=potto

Needs a checkbox and the backend has to handle this appropriately (or should we do this in the front-end somehow?).

### PR DESCRIPTION
**Pull request by daniel-wer**
This PR adds the possibility to drag&drop (multiple) nml or zip files onto the dashboard to upload them. I reused the Dropzone that is also used in the tracing view (very easy to reuse, nice work @philippotto) :)

@fm3 A flag called `createGroupForEachFile` with a string value of `"true"` or `"false"` is now sent as part of the multipart request to `/api/annotations/upload` as well. This flag indicates whether the trees of each nml file should be put into separate tree groups, or not. To wrap all trees of an nml file in a new group, create a new group with an unused groupId and assign the original tree groups as children of that new group. The name of the new group should be the name of the nml file. Additionally assign the new groupId to all trees that do not have a groupId yet. This should do the trick :)
Have a look at the `wrapInNewGroup` function in the `nml_helpers.js` if you want to see the frontend code to do this.

@philippotto After @fm3 implemented the backend part, this should be ready to test and review.

### URL of deployed dev instance (used for testing):
- https://dnddashboard.webknossos.xyz

### Steps to test:
- Drag&Drop (multiple) nml or (a single) zip file(s) to the dashboard (the activated tab shouldn't be relevant). A modal should appear that shows some basic information about those files.
- Try to upload with and without the `createGroupForEachFile` option set. The uploaded annotations should be merged, you should be redirected to the tracing view and see the merged annotation. The trees should be in separate groups or not, according to the option you set.
- The Drag&Drop upload functionality in the tracing view should work in the same way as before.
- Try to upload a faulty NML. An error message should be displayed and the upload modal should be dismissed.

### Issues:
- fixes #2926
- fixes #2972

------
- [ ] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)
- ~~[ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~~
- [x] Ready for review

### CODE REVIEW

**Comment by daniel-wer** [comment]
Maybe we should split up the snapshot.e2e.js snapshots into different snapshot files to make it easier to see what changed?! I have no idea why the changes to the snaphots in this PR are this big, and especially why thousands of lines have been added. Our tooling to deal with these snapshot changes is not existent. Maybe we can brainstorm something to make it easier to handle this.

**Comment by philippotto** [comment]
> Maybe we should split up the snapshot.e2e.js snapshots into different snapshot files to make it easier to see what changed?!

Yeah, that sounds like a good idea.

> I have no idea why the changes to the snaphots in this PR are this big, and especially why thousands of lines have been added. Our tooling to deal with these snapshot changes is not existent. Maybe we can brainstorm something to make it easier to handle this.

Maybe we can render the debug-htmls (are already emitted) with headless-chrome. We should include our default css stuff, but then it could work. But let's discuss this in person.

**Comment by fm3** [comment]
@daniel-wer the current behavior is that the tree names are prefixed with the nml filename. That seems redundant now, should I remove it? Do we have lab feedback on the desired behavior here?

**Comment by daniel-wer** [comment]
@fm3 No we don't have feedback from the lab. I'd say it's fine to remove it as in the frontend this isn't done anyways, but maybe we should get lab feedback and unify the frontend and backend behavior.

**Comment by fm3** [comment]
@daniel-wer I think that’s fine then. I noticed another thing: the prefixed tree names had the filename without the `.nml` – `name.replaceAll("\\.[^.]*$", "")` – maybe we should do that for the group names as well.

**Comment by daniel-wer** [comment]
We could also do the simpler thing and keep the nml extension as part of the group name :D I can somewhat understand to remove the extension when prefixing a tree name with the filename, but using it as the group name I'd say it's fine to include the extension. At least in the frontend nobody complained that the file extension was part of the group name :)

**Comment by fm3** [comment]
I added the corresponding backend changes, and also fixed the merging of tree groups.
I also posted in discuss for feedback on the desired behavior.

**Comment by daniel-wer** [comment]
Nice, works well for me :) Let's wait for feedback from the lab regarding the naming and then merge as soon as possible.

**Pull request merged**
