### PR TITLE
Proxy some URIs for Demo Instance

### LINKED ISSUE #5075: Proxy landing page
For the new landing page of webknossos.org, we need to proxy some routes to a different origin.

- `/` proxy only if unauthenticated
- `/features`, `/faq`, `/pricing` and probably a growing list in the future

### PR DESCRIPTION
**Pull request by fm3**
### Steps to test:
- if isDemoInstance is true, some urls should be proxied
- root should only be proxied if the user is not logged in, otherwise the normal wk main page should load

### Issues:
- fixes #5075 

------
- [x] Ready for review

### CODE REVIEW

**Comment by fm3** [comment]
@philippotto Do you know if we can force a refresh after logout (on the demoinstance) so that the user will again see the proxied `/´ ?

**Comment by philippotto** [comment]
> @philippotto Do you know if we can force a refresh after logout (on the demoinstance) so that the user will again see the proxied `/´ ?

Yes, this should be easy to do. Within the `navbar.js` module, there is a `handleLogout` function in which a `location.reload()` could be done.

**Review by youri-k — APPROVED** [review]
LGTM :shipit:

**Comment by normanrz** [comment]
Screenshot 2021-02-01 at 13 06 28
Looks like there is an encoding issue: https://proxylandingpage.webknossos.xyz/

Also, would it be possible to add support for a route wildcard (e.g. `/sw.*.js`)?

**Comment by fm3** [comment]
@normanrz should be fixed now (I also upgraded the dev instance), please try again :)

**Comment by normanrz** [comment]
I think the backend side is good!

**Review by philippotto — APPROVED** [review]
The front-end changes also lgtm!

**Comment by normanrz** [comment]
There are still 2-3 issues where the redirect to the landing page doesn't work. I'll have a look.

**Comment by normanrz** [comment]
@philippotto would you mind having a look at https://github.com/scalableminds/webknossos/pull/5083/commits/ca293ad368930b0ea29cac4e3bb90569d6bdb51d?

**Comment by philippotto** [comment]
> @philippotto would you mind having a look at [ca293ad](https://github.com/scalableminds/webknossos/commit/ca293ad368930b0ea29cac4e3bb90569d6bdb51d)?

lgtm!

**Pull request merged**
