### PR TITLE
Add layer name to jobs table entry of tiff export job

### PR DESCRIPTION
**Pull request by MichaelBuessemeyer**
This pr adds the layer name to every version of the export tiff job. Previously the names of volume layers were the fallback layers' names if they existed. See
image

Now the name of the volume layer is used in every case. Even when the volume layer has no fallback.

image

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- I suggest testing locally as a wk-worker is needed for testing.
- You need a running instance of the wk worker that is registered in the database (`yarn enable-jobs`)
- Open an annotation of any dataset with at least one color layer and a segmentation layer.
- create a small bounding box that has only 1 slice in z direction. The smaller the bounding box the faster the jobs are executed.
- Then use the download button in the bounding box tab and start a export job for one color layer and one volume layer without having drawn anything on that volume layer.
- Close the export modal, draw something in the just exported volume layer within the bounds of the bounding box.
- Create a new annotation layer without a fallback layer.
- Also draw something on the new volume layer without fallback within the bounding box. 
- Trigger another export job for volume layer with fallback layer and the volume layer without fallback layer.
- Go to the jobs page. Each export tiff job entry should have the exported's layer's name in it and if it is a volume annotation layer that was exported, there should be a link pointing to the annotation. Else the link should link to the dataset in view mode.

### Issues:
- fixes #[6297](https://github.com/scalableminds/webknossos/issues/6297)

------
(Please delete unneeded items, merge only when none are left open)
- [x] Ready for review

### CODE REVIEW

**Comment by MichaelBuessemeyer** [comment]
First thing:
@daniel-wer I do not know whether you have an installed version of the wk-worker locally. If you do not have one, please ask Philipp to review this pr. The review should be pretty fast and setting up the wk-worker locally only to review this pr is not worth it in my opinion.

I am unsure about the formulation of the export job entry in the table (see the 2nd screenshot in the pr description). The two "of"s in the sentence sound quirky. Do you have a better formulation @daniel-wer?

**Comment by daniel-wer** [comment]
Unfortunately, I don't have a working wk-worker setup, locally, so I'll reassign the review.

**Comment by daniel-wer** [comment]
> I am unsure about the formulation of the export job entry in the table (see the 2nd screenshot in the pr description). The two "of"s in the sentence sound quirky. Do you have a better formulation @daniel-wer?

Hmm, I would switch the of and from, move "layer" in front of the label and add "dataset" in front of the dataset name, so that it reads "Tiff export of layer {layerLabel} from dataset ...". With the annotation part it could then read "Tiff export of layer {layerLabel} from annotation of dataset ...".

**Review by philippotto — APPROVED** [review]
Looks good to me :+1: Since your testing steps are so thorough and backed with a screenshot, I think, another testing round is not necessary. Especially, since the changes are unlikely to break anything mission critical. Let me know in case you disagree. Otherwise, feel free to merge :)

**Comment by MichaelBuessemeyer** [comment]
> I think, another testing round is not necessary.

Ok, thanks and let go :shipit:

**Pull request merged**
