### PR TITLE
Make "Go to center of bounding box" available at one click

### LINKED ISSUE #8001: Make go to center of BBox a priority
## Detailed Description

Currently, jumping to the center of a bbox is only available via the menu in a bbox tab entry but it is a frequent use case to jump to the bbox. However, the color picker for the bounding boxes is not such a frequent action. Therefore, I suggest to move the color picker into the bbox menu and pull the "move to center" out into an easily accessible button where the color picker is currently located. 

## Context

* [ ] Specific to long-running jobs (set `jobsEnabled=true` in `application.conf`)
* [ ] Specific to webknossos.org (set `isDemoInstance=true` in `application.conf`)

### PR DESCRIPTION
**Pull request by dieknolle3333**
### URL of deployed dev instance (used for testing):
- https://centerbbsingleclick.webknossos.xyz/

### Steps to test:
- Open an annotation with some bounding boxes
- Click anywhere in a bounding box entry. This should center the bounding box within the view ports
- Editing the color, the name, the coordinates, clicking the context menu or any of its entries or switching the visibility shouldnt center the bbox
- the rest of the UI should be working as before

### TODOs:
- [x] editing the coordinates or the color shouldnt focus bbox

### Issues:
- fixes #8001

------
(Please delete unneeded items, merge only when none are left open)
- [x] Updated [changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [ ] Updated [migration guide](../blob/master/MIGRATIONS.unreleased.md#unreleased) if applicable
- [ ] Updated [documentation](../blob/master/docs) if applicable
- [ ] Adapted [wk-libs python client](https://github.com/scalableminds/webknossos-libs/tree/master/webknossos/webknossos/client) if relevant API parts change
- [ ] Removed dev-only changes like prints and application.conf edits
- [x] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)
- [ ] Needs datastore update after deployment

### CODE REVIEW

**Comment by philippotto** [comment]
cool!! ideally, the cursor should also indicate that the entire row is clickable. this should work with css (`cursor: pointer`).

**Comment by philippotto** [comment]
getting there :smile: unfortunately, the hover target area is not identical to the click target area. clicking close to the edge does not work (the cursor also rightfully indicates that):

image

maybe a margin or padding needs to be adapted or the click handler (+ css class) needs to be one level further up in the hierarchy?

**Comment by dieknolle3333** [comment]
Very good point! I think I fixed it :)

**Review by philippotto — APPROVED** [review]
awesome! feels really slick :)

**Pull request merged**
