### PR TITLE
added timestamp option to UpdateActions

### LINKED ISSUE #2418: save updateActionGroup timestamps in rocksdb
currently only the createNode timestamps can be used when reconstructing missing timespan logs

### PR DESCRIPTION
**Pull request by youri-k**
- added a timeStamp-field to reconstruct timelogs

### Issues:
- fixes #2418 

------
- [x] Ready for review

### CODE REVIEW

**Comment by youri-k** [comment]
Currently I'm trying to solve the automatic serialization of the UpdateActions

**Comment by youri-k** [comment]
@fm3 I fixed the serialization, but sadly I couldn't avoid some code duplication
Maybe you have an idea on how to avoid it?

**Comment by fm3** [comment]
No, this is about what i had in mind. I don’t know how to reduce this duplication without losing backwards compatibility. One thing I noticed: since some of the update actions already have a timestamp value (with a different semantics – e.g. the timestamp of the created node), I would rename this new field to actionTimestamp or something like that, to avoid confusion.
Did you test if update actions saved with the old code can be loaded and applied to construct tracings with the new code?

**Comment by daniel-wer** [comment]
Is this ready to be merged tomorrow? :)

**Pull request merged**
