### PR TITLE
Enable End-to-end tests again

### PR DESCRIPTION
**Pull request by daniel-wer**
This PR aims to reduce the flakiness of the e2e tests to a minimum, so they can be enabled again.
It updates all e2e related dependencies to the current versions (webdriver, selenium, firefoxdriver, ...).

The biggest change is that the tests are now executed synchronously. With v4 webdriver.io switched to synchronous execution and although async is possible via a flag, according to their docs, they focus on and especially test the synchronous versions. I tried the sync versions and got very promising results, which is why I switched all e2e tests to synchronous.

Currently there is one test consistently failing on Jenkins. I'm still investigating. Jenkins uses Firefox 52, whereas locally I use Firefox 54 and I cannot reproduce the issue. I installed 52 locally and got the same error, so it's probably related to that version of Firefox. As far as I could see, we're using the Firefox ESR version in our Docker build, which is 52. Would it be possible to use the up-to-date version instead @normanrz ?

Before merging the `logLevel` in the wdio.conf should be reset to "error".

### Steps to test:
- Run `sbt test` to run the e2e tests

------
- [ ] Ready for review

### CODE REVIEW

**Comment by daniel-wer** [comment]
I believe I fixed the failing test.
I do not like that the execution took 3m 29s, but switching from async to sync didn't make it much worse
 (execution time was >3m before as well).

I had some success running with `maxInstances: 3` locally, but this will probably sometimes lead to failing tests, because of db interactions.

**Comment by jstriebel** [comment]
@daniel-wer : Thanks for getting back on this! :crown: 
Ppdating to some newer Firefox includes updating to debian testing ([see here](http://mozilla.debian.net/)), which I would try to avoid. If it is fine so far, I would stick to firefox-esr for now.

**Comment by normanrz** [comment]
@jstriebel because of code-transpilation we only really support the last two stable versions of firefox. can install use firefox from a different source in the test image?

**Comment by jstriebel** [comment]
We can also download the newest version from the homepage or try to use the ubuntu ppa. I will have a look next week.

**Comment by normanrz** [comment]
Since the e2e take so long, should we keep them in the isolated build process that runs every morning?

**Comment by daniel-wer** [comment]
We could do that, I'm not sure who would feel responsible if they break then though. Let's discuss this later today in person.

**Comment by hotzenklotz** [comment]
Code looks ok, but I can't get it to run. `sbt test` starts and compiles one file but never actually starts the server and executes the tests. :-( 
Perhaps, @jstriebel can run the test once and confirm that it works on his machine.

**Comment by daniel-wer** [comment]
Ah ok you waited :D Yes it took quite a while for me as well when running it for the first time.

**Comment by hotzenklotz** [comment]
Now it finished. All tests passed. Great.

@daniel-wer Don't forget to lower the log level before merging.

**Comment by daniel-wer** [comment]
I'll let Jenkins do 50 runs of the tests tonight to measure how reliable they are.
After that I'll revert the log level and merge if the reliability is ok.

**Comment by daniel-wer** [comment]
I ran the tests 50 times last night, results not very promising yet, but also not too bad ^^
49 runs of the 50 failed.
One test failed 49 times, another 7 times, no other test failed.

So I'll have a look at the two tests and do another run afterwards.

**Comment by normanrz** [comment]
49 of 50 failed xD

**Comment by hotzenklotz** [comment]
Lol. You last commit seems promising. The task tab loading spinners are fairly new and the tests were not adapted.

**Comment by daniel-wer** [comment]
The new run was more successful, 3 out of the 50 runs failed.
Two of those runs failed because webdriver couldn't connect to Selenium/Firefox/idk:
```
ERROR: connection refused
remote stacktrace: stack backtrace:
   0:           0x57af6d - backtrace::backtrace::trace::h59229d13f6a8837d
   1:           0x57b0c2 - backtrace::capture::Backtrace::new::h23089c033eded8f0
   2:           0x4472fc - webdriver::error::WebDriverError::new::h0b226f62ff19e120
   3:           0x4514c1 - geckodriver::marionette::MarionetteHandler::create_connection::hd468f55550be3626
   4:           0x426854 - <webdriver::server::Dispatcher<T, U>>::run::h62323eaff3e71b8c
   5:           0x40935c - std::panicking::try::do_call::hb7e6ff6d130a72cf
   6:           0x5de23a - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:98
   7:           0x41c003 - <F as alloc::boxed::FnBox<A>>::call_box::hd6ceeda495c4fa0e
   8:           0x5d68d4 - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:650
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84
```

Not sure what this means and I couldn't find anything quickly.

The third fail was this:
```
[firefox #0-0] 1) Taskssuite3 should have one available task:
[firefox #0-0] Failed: An element could not be located on the page using the given search parameters.
[firefox #0-0] Error: An element could not be located on the page using the given search parameters.
[firefox #0-0]     at click("#tab-tasks") - at element("#tab-tasks") - click.js:12:17
```

I think we can go ahead and merge this.

**Comment by normanrz** [comment]
@daniel-wer is this ready to merge?

**Pull request merged**
