### PR TITLE
Fix dropdown login padding

### LINKED ISSUE #3956: Login dropdown layout issue
Bildschirmfoto 2019-03-28 um 13 19 16

### PR DESCRIPTION
**Pull request by MichaelBuessemeyer**
This PR adds a margin between the `forgot password` and `Register Now` in the login dropdown and thus ensures some space between them. I also made the position of the dropdown fixed so that it does not scroll away anymore.

### URL of deployed dev instance (used for testing):
- [https://fixdropdownloginissue.webknossos.xyz](https://fixdropdownloginissue.webknossos.xyz)

### Steps to test:
- logout and open the dropdown. Resize the window and try to get the two options `forgot password` and `Register Now` together. There should be at least some space between them. 
- Testing that the dropdown does not scroll away: add some `margin-bottom` to the main container so that it becomes scrollable :)

### Issues:
- fixes #3956

------
- ~~[ ] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)~~
- ~~[ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes~~
- ~~[ ] Needs datastore update after deployment~~
- [x] Ready for review

### CODE REVIEW

**Comment by philippotto** [comment]
Thanks for doing this and also for implementing the `fixed` fix :)

I noticed, that it can happen that the links are not next to each other when resizing the window. You can enforce the correct layout, by using a flexbox. The markdown should look something like this:

```
// warning: this is not jsx but html
<div style="display: flex;">
  <a href="/auth/register" style="margin-right: 10px; flex-grow: 1;">Register Now</a>
  <a href="/auth/resetPassword">Forgot Password</a>
</span>
```

**Comment by MichaelBuessemeyer** [comment]
@philippotto nice notice :+1: , but the changes you suggested do not fix this problem for me. But let's talk about this together :slightly_smiling_face:

**Comment by MichaelBuessemeyer** [comment]
@philippotto I updated the dev instance with your suggested changes. They seem to work but I think the solution is not ideal, as the links now get displayed like a table :confused:

**Comment by philippotto** [comment]
> @philippotto I updated the dev instance with your suggested changes. They seem to work but I think the solution is not ideal, as the links now get displayed like a table

Thank you! I just added `white-space: nowrap;` to the two `a` elements. Let's hope, this works :)

**Comment by MichaelBuessemeyer** [comment]
@philippotto I updated the dev instance and your fix works perfectly :+1:

**Pull request merged**
