### PR TITLE
[WIP] Add diameter measurement tool

### LINKED ISSUE #3395: Add-on for measuring diameter of neurites
[Link to Discuss](https://discuss.webknossos.org/t/add-on-for-measuring-diameter-of-neurites/1190/2)

### PR DESCRIPTION
**Pull request by MichaelBuessemeyer**
Add a diameter measurement tool to the frontend of wk. The tool shall have an ellipse-like shape and can be resized with to radii. Rotation should also be possible. The extent of the radii should be displayed to the user and also saved. The diameter can be only set around a node.

For further reading: here is the [discuss post](https://discuss.webknossos.org/t/add-on-for-measuring-diameter-of-neurites/1190/8)

=> This is currently not a clean version, please do not review the code yet @philippotto.

### URL of deployed dev instance (used for testing):
- [https://diametermeasurementtool.webknossos.xyz/](https://diametermeasurementtool.webknossos.xyz/)

### Steps to test:
- open a skeleton tracing
- create some node
- if you have an active node you can enable the diameter in the settings on the right side of the page (Nodes & Trees => Enable Diameter Measurement tool)
- The shortcuts for manipulating the diameter are 4, 5 and 6:

-   4 and 5 increase the two radii (dof1 and dof2).
    Additionally pressing shift will decrease them.
-  6 will rotate the diameter (dof3)
    Use shift to change the rotation direction.

### Issues:
- fixes #3395

------
- [ ] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)
- ~~[ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~~
- [ ] Updated [documentation](../blob/master/docs) if applicable
- ~~[ ] Needs datastore update after deployment~~
- [ ] Ready for review

### CODE REVIEW

**Comment by philippotto** [comment]
I'm closing this PR, as we put this into backlog effectively. We can resurrect when needed.

**Comment by philippotto** [comment]
Potential todos:
- [ ] bring branch up to date
- [ ] make compatible with ortho mode
- [ ] display measured values somewhere
- [ ] store measurements per node so that they are persisted when downloading as NML

**Comment by MichaelBuessemeyer** [comment]
According to the discussion, ortho mode is not a top priority feature

**Comment by MichaelBuessemeyer** [comment]
I added the additional property `diameterProperties` to skeleton nodes. The property is an object with the following structure: 
```
DiameterProperties = {
  xRadius: number,
  yRadius: number,
  scaledXRadius: number,
  scaledYRadius: number,
  rotation: number,
}
```
The whole property is optional and can be undefined for nodes.
Now a whole node looks like this:
```
{
bitDepth: 8
diameterProperties: {
  rotationAngle: 0
  scaledXRadius: 89.24559811617618
  scaledYRadius: 89.24559575667777
  xRadius: 20
  yRadius: 20 }
id: 45084
interpolation: true
position: (3) [766, 344, 568]
radius: 1
resolution: 0
rotation: (3) [0, 343.45213704002293, 0]
timestamp: 1570700579903
treeId: 38
viewport: 4
}
```

@youri-k Could you please change the backend that it understands updateActions of nodes with the new property? The nml generation also needs to store the new property.
Thanks a lot :)

**Comment by fm3** [comment]
Backend part for storing/serializing DiameterProperties LGTM. However, let’s discuss if in NML it may make more sense to use additional attributes for the Node, rather than a child node.

**Comment by youri-k** [comment]
@fm3 I agree with you so I changed the `diameterProperties` to additional attributes. Please have another look especially at the existence testing :)

**Comment by fm3** [comment]
Works for me @youri-k , the option.get is of course a bit annoying but I see that strictly functional methods would probably be harder to read there.

One more thought: I’m not sure about the semantics, right now the attributes like `rotationAngle` and `scaledYRadius` are node attributes. Should they possibly be prefixed to mark them as part of the diametr measurement tool? Or does mit make sense to simply have them be part of  nodes? I do not know this, as I’ve never seen this tool in action. What do you think @philippotto @MichaelBuessemeyer ?

**Comment by MichaelBuessemeyer** [comment]
TODO: reduce the number of update actions for diameter properties

**Pull request closed without merging**
