### PR TITLE
Second try: Upgrade to Play 2.9

### PR DESCRIPTION
**Pull request by fm3**
Reverts scalableminds/webknossos#7419 as a second try for https://github.com/scalableminds/webknossos/pull/7366 – we had to roll that one back because of incompatible silhouette version, originally yielding `java.lang.NoSuchMethodError: 'void play.api.mvc.Result.<init>(play.api.mvc.ResponseHeader, play.api.http.HttpEntity, scala.Option, scala.Option, scala.collection.immutable.Seq)'` at `io.github.honeycombcheesecake.play.silhouette.api.services.AuthenticatorResult.<init>(AuthenticatorService.scala:47)` (called by us during login)

This is now fixed in silhouette 9.0.0 by https://github.com/playframework/play-silhouette/pull/40

### Dev deployment for testing

https://revertrevertplay.webknossos.xyz/

### TODO
 - [x] migrate CSPFilters config (done in #7450)
 - [x] wait for compatible silhouette release (it’s [here](https://github.com/playframework/play-silhouette/releases/tag/9.0.0))

### CODE REVIEW

**Comment by philippotto** [comment]
> I would hope that [playframework/play-silhouette#40](https://github.com/playframework/play-silhouette/pull/40) fixes that, so let’s wait for that.

Seems to be merged now :)

**Comment by mkurz** [comment]
> Seems to be merged now :)

Not ready yet however, please be patient :wink:

**Review by frcroth — APPROVED** [review]

**Comment by mkurz** [comment]
Are you planing to upgrade to Play 3?

**Comment by fm3** [comment]
@mkurz Probably, yes. We’ll have a look at that early next year. We have a couple of usages of akka ourselves, but it may be simple to migrate those to pekko.

**Pull request merged**
