### PR TITLE
ESC and Enter to blur vector inputs

### LINKED ISSUE #4054: ESC to blur position textbox
Remove the focus when pressing ESC after typing into the position textbox

### PR DESCRIPTION
**Pull request by MichaelBuessemeyer**
This PR makes it possible to blur all vector inputs (inputs that require multiple numbers) by hitting Esc or enter.

### URL of deployed dev instance (used for testing):
- [https://makevectorinputsblurable.webknossos.xyz](https://makevectorinputsblurable.webknossos.xyz)

### Steps to test:
- Open a tracing in flight mode. Try editing the position and rotation and blurring them with Esc and enter.

### Issues:
- fixes  #4054

------
- ~~[ ] Updated [changelog](../blob/master/CHANGELOG.md#unreleased)~~ -> I don't think this is needed, right?
- ~~[ ] Updated [migration guide](../blob/master/MIGRATIONS.md#unreleased) if applicable~~
- ~~[ ] Updated [documentation](../blob/master/docs) if applicable~~
- ~~[ ] Adapted [wk-connect](https://github.com/scalableminds/webknossos-connect) if datastore API changes~~
- ~~[ ] Needs datastore update after deployment~~
- [x] Ready for review

### CODE REVIEW

**Comment by philippotto** [comment]
Could you also do the same for editing tree names and comments? See: https://discuss.webknossos.org/t/lose-textbox-focus-when-pressing-esc-and-possibly-enter/1402

**Comment by MichaelBuessemeyer** [comment]
@philippotto @daniel-wer Currently enter and esc trigger the same effect of blurring and then saving the changes. But I think using ESC should not save the changes, it should discard them. Do you agree?

**Comment by MichaelBuessemeyer** [comment]
@daniel-wer If you think the current behavior is fine, could you please review my newest changes? 
I added a general wrapper for the antd input that adds the wanted "blur behavior". This can now be used for every Input you want. 
But I think the name of the wrapper (`BlurrableInput`) is still debatable ... :sweat_smile: But I could not come up with something better.

**Comment by daniel-wer** [comment]
LGTM :+1:

**Pull request merged**
