### PR TITLE
Fix error message on localFolderWhitelist

### PR DESCRIPTION
**Pull request by normanrz**

### CODE REVIEW

**Review by fm3 — APPROVED** [review]
to be honest I think localFolderWhitelist is not a good name for this config setting. While we’re here, maybe we should clean that up. I think to avoid confusion, we should use “Folder” only in context of the virtual in-database folders used for the dashboard, and “Directory” or “Path” everywhere else, if possible. What do you think?

However, if you need this to produce a readable error message quickly, feel free to merge this as is first and we’ll do the cleanup renaming later.

**Comment by normanrz** [comment]
Fair enough. We can change the name of the key. Is that actually a per-datastore config?

**Comment by fm3** [comment]
> Is that actually a per-datastore config?

Yes, as it is assumed that datastores can each have their own filesystem. The wk side never reads this config value, only the datastore module.

**Comment by fm3** [comment]
Looks like this is messed up more than I expected, the wk side also reads this list from the datastore config block, to assert this during exploring. I think that does not really make sense with a multi-datastore setup. I’ll have to have a closer look at this stuff.

**Comment by fm3** [comment]
Follow-up issues https://github.com/scalableminds/webknossos/issues/7781 and https://github.com/scalableminds/webknossos/issues/7780

Should’t block this error message fix.

**Pull request merged**
