### PR TITLE
Switch to root folder if current folder cannot be loaded

### LINKED ISSUE #7658: When  dashboard localstorage points to deleted folder, go to root instead
Currently, the »could not find the requested folder« toast is shown but no datasets and no folder tree. Only after Refresh you see the root folder again. My test case is re-visiting the dashboard after `yarn refresh-schema`.

Could this situation do this refresh automatically (fetch the new folder tree, display root)?

This would greatly improve developer convenience and I think it also makes sense for users (someone else may have deleted a folder in the meantime)

### PR DESCRIPTION
**Pull request by philippotto**
### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- create a new folder
- yarn refresh-schema
- reload page

### Issues:
- fixes #7658

------
(Please delete unneeded items, merge only when none are left open)
- [x] Updated [changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)

### CODE REVIEW

**Comment by fm3** [comment]
I’m afraid this doesn’t quite work for me yet :grimacing: It looks like some folders briefly flash but then it switches to the blank version again after a few ms. Does it work for you, did you test with refresh-schema? I don’t know what’s different, maybe it’s a firefox vs chrome thing? :thinking:

**Comment by philippotto** [comment]
> I’m afraid this doesn’t quite work for me yet 😬 It looks like some folders briefly flash but then it switches to the blank version again after a few ms. Does it work for you, did you test with refresh-schema? I don’t know what’s different, maybe it’s a firefox vs chrome thing? 🤔

Initially, I simply tried `localStorage.setItem("sample@scm.io-sample_organization-activeFolderId", "65e871d4ec0000dc04353aee")` and then reloaded the page. That worked even on master. Then, I tried `yarn refresh-schema` which was problematic. With my fix, a simple reload worked. However, something might have changed inbetween.
Maybe the folder hierarchy is cached internally and if that cache is outdated, the switch to the root doesn't work.
I'll look into it again :shrug: 

It's a bit annoying to test since refreshing the schema takes so long. Do you know whether there is a faster way to clear the folders?

**Comment by fm3** [comment]
I’m afraid manually editing folders in the DB is not going to be simpler or faster than yarn refresh-schema :/

**Comment by philippotto** [comment]
Please try again! I think it already worked before, but there was quite a bit of a delay until the switch would happen. The active folder is fetched and if that fails, it is retried three times. Due to an exponential back off in the delay time (default of react-query), this took at least 6 seconds. Now, it's down to 1.5s. I hope this wait is acceptable :)

By the way, deleting the `rm -f target/scala-2.13/src_managed/schema/com/scalableminds/webknossos/schema/Tables.scala` bit from `yarn refresh-schema` helped a bit :)

**Comment by philippotto** [comment]
Unfortunately, it's not trivial :S

**Review by fm3 — APPROVED** [review]

**Pull request merged**
