### PR TITLE
Check datastore health when requests error

### PR DESCRIPTION
**Pull request by philippotto**
This PR adds a very simple health check mechanism to our request module. When a request failed (for whatever reason), we will ping the datastore health endpoint and display a warning in case the status is not 200.

@fm3 The healthcheck is currently done by pinging `data/health` on wk (which redirects to the actual datastore). I think that's alright, since it doesn't really matter whether the datastore is up when wk is down. Do you agree?

### Mailable description of changes:
 - WebKnossos will notify users when the datastore is not available (e.g., due to an update) and ask them 
to check back later.

### Steps to test:
- ~This was quite hard to test, since the datastore and wk itself are run together locally. I disabled the client-validation for bulk task creation and changed the `catch` in `checkDataStoreHealth` to `then`. As long as the health endpoint works as expected, everything should work fine. But maybe @fm3 knows of a better way to test this.~
- Set up: [Here is how to set up a standalone-datastore locally](https://github.com/scalableminds/webknossos-wiki/wiki/Set-up-a-standalone-datastore-locally)
- Create a new task & try to get a new task --> should work
- Get another new task -> should fail with no datastore-related error message
- Open a dataset --> should work
- Kill the datastore
- Create a new task & try to get a new task --> should fail with a warning about the datastore
- Open a dataset --> shouldn't display data (but instead warn about the datastore)

### Issues:
- contributes to #2604

------
- [X] Ready for review

### CODE REVIEW

**Comment by fm3** [comment]
Cool! I’ll have a closer look tomorrow. But I can already say that `data/health` in wK does not exist if there is no local datastore. (you can try in the production instance, should say Action not found)

**Comment by fm3** [comment]
Here is how to set up a standalone-datastore locally:

- in `conf/application.conf`, disable the local datastore
     - (comment out `play.modules.enabled += com.scalableminds.webknossos.datastore.DataStoreModule"` with a `//`)
     - add `enabled = false` within the `datastore { … } ` block
- run `tools/postgres/refresh_schema.sh`
- on the created database, run with SQL: `insert into webknossos.datastores(name, url, key, typ, isdeleted) values('standalone-9090', 'http://localhost:9000', 'something-secur3', 'webknossos-store', false)`

next, you need three shells:
- in the first, run `./fossildb/run.sh`
- in the second, run `sbt "webknossosDatastore/run 9090 -Dconfig.file=webknossos-datastore/conf/standalone-datastore.conf"`
- in the third, run `sbt run`

next, in a browser
- navigate to `localhost:9000` to make wK launch
- navigate to `localhost:9090` to make standalone-datastore launch (should display action not found page)
- back in the wK tab, click the refresh button in dataset list view, you should then see datasets.

**Comment by fm3** [comment]
when a wK request fails due to an unsuccessful backend-internal datastore request, it should reply something like this:

```


{
  "messages": [
    {
      "error": "annotation.create.failed"
    },
    {
      "chain": " <~ Error sending WS request to http:\/\/localhost:9090\/data\/tracings\/skeleton\/save (ID: 2): Connection refused: localhost\/127.0.0.1:9090\ncom.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:128)\n    …"
    }
  ]
}
```

so maybe from there you could extract the datastore url to then query its health endpoint. I can also adapt the backend to add a specific message for datastore requests in the chain (WS requests are more generic).

**Comment by philippotto** [comment]
Thanks, @fm3. Resulting from our discussion, I implemented the following logic:

- On each failed request
  - check whether the used url belongs to a datastore (check against the cached output of getDatastores() endpoint)
  - check whether the error chain mentions an URL which belongs to a datastore
- Datastores which are considered related to the error are pinged using the /health endpoint. If the endpoint doesn't return 200, show an error.

This strategy might not be the most elegant one, but it should be quite robust, I think.

@daniel-wer I updated the test plan for this PR. So feel free to give it a try.
Code wise: The request library now depends on the rest api (and vice versa) which is not really great, but I think it's ok, as we don't use the library for anything else, anyway.

**Comment by philippotto** [comment]
@daniel-wer @fm3 Can you give the branch a try (and/or review it)? :)

**Pull request merged**
