### PR TITLE
adds button for duplicating annotations

### LINKED ISSUE #5570: Create Duplicate of Annotation
There is “copy to my account” if you view someone else’s annotation. Sometimes you want to do the same for one of your own annotations. The backend should already support this :tm:

### PR DESCRIPTION
**Pull request by normanrz**
### Steps to test:
- Open an annotation (yours or from somebody else)
- Open the menu next to "save", click duplicate
- The current annotation will be saved, a duplicate will be created and you will be redirected to the duplicate

### Issues:
- fixes #5570

------
(Please delete unneeded items, merge only when none are left open)
- [x] Updated [(unreleased) changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [x] Updated [documentation](../blob/master/docs) if applicable
- [x] Ready for review

### CODE REVIEW

**Review by philippotto — APPROVED** [review]
lgtm :+1:

**Comment by normanrz** [comment]
@philippotto Can you think of situations when we don't want to allow duplicating?

**Comment by philippotto** [comment]
> @philippotto Can you think of situations when we don't want to allow duplicating?

no, even if we would forbid it in certain circumstances, downloading+reuploading would be a workaround, anyway (which we don't forbid, either).

**Comment by normanrz** [comment]
> > @philippotto Can you think of situations when we don't want to allow duplicating?
> 
> no, even if we would forbid it in certain circumstances, downloading+reuploading would be a workaround, anyway (which we don't forbid, either).

Well, there is an `allowDownload` restriction.

**Comment by fm3** [comment]
allowDownload is currently always identical to allowAccess

**Pull request merged**
