### PR TITLE
Fix performance bottleneck when deleting a lot of trees at once

### PR DESCRIPTION
**Pull request by daniel-wer**
Also fix a bug when importing an NML with groups when only groups but no trees exist in an annotation.
Also fix a bug where trying to delete a non-existing node (via the API, for example) would delete the whole active tree (at least that's what it looked like to me when reading the code).

### URL of deployed dev instance (used for testing):
- https://___.webknossos.xyz

### Steps to test:
- Create an annotation with more than 10,000 trees and delete them all at once. This should take less than a second and not multiple minutes.
- Also test other tree deletion related functionality:
  - Tree multi-select and deletion
  - Group deletion with and without children
  - Single tree deletion
- Import an NML with groups. Delete all but one group and import the NML again. On master, the newly imported group gets the same ID as the one that was not deleted before, leading to all sorts of issues. If only one of the groups gets the blueish selected background, the fix works.

See this gif for deleting 50,000 trees at once:
batched_tree_deletion

### Issues:
- fixes performance bottleneck

------
(Please delete unneeded items, merge only when none are left open)
- [x] Updated [changelog](../blob/master/CHANGELOG.unreleased.md#unreleased)
- [x] Removed dev-only changes like prints and application.conf edits
- [x] Considered [common edge cases](../blob/master/.github/common_edge_cases.md)

## Release Notes

- **New Features**
  - Enhanced efficiency for deleting multiple trees through batch actions.
  - Improved user interface interactions by ensuring context menus close after delete actions.

- **Bug Fixes**
  - Resolved a performance bottleneck when deleting numerous trees simultaneously.
  - Fixed issues related to importing NML files with groups and deleting non-existing nodes via the API.

- **Performance Improvements**
  - Asynchronous image file reading for better performance.
  - Improved error handling for clearer context in error messages.

These updates significantly enhance user experience and system performance.

### CODE REVIEW

**Review by hotzenklotz — APPROVED** [review]
Code LGTM. Haven't tested yet.

**Review by MichaelBuessemeyer — CHANGES_REQUESTED** [review]
Thanks a lot for all these awesome fixes :tada:

> Import an NML with groups. Delete all but one group and import the NML again. On master, the newly imported group gets the same ID as the one that was not deleted before, leading to all sorts of issues. If only one of the groups gets the blueish selected background, the fix works.

Nice ;fix works :tada:

One unrelated thing I noticed is that under linux (ubuntu + chrome) the tree context menu does not close after clicking on delete or shuffle tree color. I would have expected for the context menu to close at least after the delete action was clicked, because the tree for with the context menu was opened does not exist anymore. Thus, the context menu points to a deleted tree and imo should be closed directly when hitting the deletec menu item.
Do you think you can also take a look at this in this pr or do you want to do this as a follow-up?

Moreover:
> Also fix a bug where trying to delete a non-existing node (via the API, for example) would delete the whole active tree (at least that's what it looked like to me when reading the code).

While testing this with 
[bug_test.nml.txt](https://github.com/user-attachments/files/17676736/bug_test.nml.txt)
(and having tree with id 2 (the blue one) active), I get the following error in the console:
image

Here is my mini test API script:  
```javascript
window.webknossos.apiReady(3).then(api => {
    const activeTreeId = api.tracing.getActiveTreeId();
    api.tracing.deleteNode(100, activeTreeId);
  });
```
Could you maybe give this a little try to avoid the `UnhandledRejection: "Error: Get empty"`?

At least, I hope that me trying to reproduce what you meant with was correct
> Also fix a bug where trying to delete a non-existing node (via the API, for example) would delete the whole active tree (at least that's what it looked like to me when reading the code).

**Comment by MichaelBuessemeyer** [comment]
Oh an the rest of the deletion fixes worked perfectly. Thanks a lot :fire: :racing_car:

**Comment by daniel-wer** [comment]
Thanks for the review @MichaelBuessemeyer!

> One unrelated thing I noticed is that under linux (ubuntu + chrome) the tree context menu does not close after clicking on delete or shuffle tree color.

Fixed :+1: 

> Could you maybe give this a little try to avoid the UnhandledRejection: "Error: Get empty"?

Thank you for testing this! Looks like the "bug" I fixed couldn't actually be triggered through the api. Still, I think the code is more explicit and correct now, so I'd leave it as-is. I adapted the code to avoid the thrown error in case of a non-existing node id. This is in line with the other accessor functions and in the spirit of the used Maybe pattern I'd argue.

**Review by MichaelBuessemeyer — APPROVED** [review]
Awesome, thanks for fixing the nitpicks :pray:

**Pull request merged**
